<div class="container main">
	<div class="row">
		<div class="col-md-9">
			<h2>ಪ್ರವಚನಗಳ ವೀಡಿಯೊಗಳು</h2><br />
			<h4 class="text-left"><?=$data['title']?></h4>
			<iframe width="800" height="520" src="https://www.youtube.com/embed/<?=$data['id']?>?autoplay=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
		</div>
		<div class="col-md-3">
			<h3>Related Videos</h3><br />
			<div class="row videoSidebar justify-content-around">
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/RtQXPPhTGV8/Kannada Song On Essence Of Vedantha"><img src="<?=PUBLIC_URL?>images/stock/video-covers/001.jpg" alt="Kannada Song On Essence Of Vedantha" /><p class="sideBarText">Kannada Song On Essence Of Vedantha</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/TmsRhWs81oU/Adbhuta Shankara - Shankara Jayanthi Special Lecture"><img src="<?=PUBLIC_URL?>images/stock/video-covers/002.jpg" alt="Adbhuta Shankara - Shankara Jayanthi Special Lecture" /><p class="sideBarText">Adbhuta Shankara - Shankara Jayanthi Special Lecture</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/fsBJuQTVFHc/Adiyakaanade Arasi Balalide"><img src="<?=PUBLIC_URL?>images/stock/video-covers/003.jpg" alt="Adiyakaanade Arasi Balalide" /><p class="sideBarText">Adiyakaanade Arasi Balalide</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/Ao8cCfVBrpI/Mareyadiro Maanavane"><img src="<?=PUBLIC_URL?>images/stock/video-covers/004.jpg" alt="Mareyadiro Maanavane" /><p class="sideBarText">Mareyadiro Maanavane</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/rzFMojQ19eA/Chaandogya Upanishat"><img src="<?=PUBLIC_URL?>images/stock/video-covers/005.jpg" alt="Chaandogya Upanishat" /><p class="sideBarText">Chaandogya Upanishat</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/VC7QUUMwvbs/Taittireeya Upanishat (krishnayajurvedeeya)"><img src="<?=PUBLIC_URL?>images/stock/video-covers/006.jpg" alt="Taittireeya Upanishat (krishnayajurvedeeya)" /><p class="sideBarText">Taittireeya Upanishat (krishnayajurvedeeya)</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/USrCP7xuO-w/Shravanada Mahatva"><img src="<?=PUBLIC_URL?>images/stock/video-covers/007.jpg" alt="Shravanada Mahatva" /><p class="sideBarText">Shravanada Mahatva</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/2RwQdNSgPWc/Brahmajnaanada Mahime"><img src="<?=PUBLIC_URL?>images/stock/video-covers/008.jpg" alt="Brahmajnaanada Mahime" /><p class="sideBarText">Brahmajnaanada Mahime</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/LIMsTBG1jXs/Vidye Avidye &amp; Bhajans By H. H. Swamiji"><img src="<?=PUBLIC_URL?>images/stock/video-covers/009.jpg" alt="Vidye Avidye &amp; Bhajans By H. H. Swamiji" /><p class="sideBarText">Vidye Avidye &amp; Bhajans By H. H. Swamiji</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/32aMJvkn2hM/Advaitavu Mathavalla- Bold Voice Of H.h.swamiji In 1972"><img src="<?=PUBLIC_URL?>images/stock/video-covers/010.jpg" alt="Advaitavu Mathavalla- Bold Voice Of H.h.swamiji In 1972" /><p class="sideBarText">Advaitavu Mathavalla- Bold Voice Of H.h.swamiji In 1972</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/1DIctNmpss0/Vyvahaara Endarenu, Voice Of H H Satchidaanandendra Saraswathi Swamiji Of Holenarasipur"><img src="<?=PUBLIC_URL?>images/stock/video-covers/011.jpg" alt="Vyvahaara Endarenu, Voice Of H H Satchidaanandendra Saraswathi Swamiji Of Holenarasipur" /><p class="sideBarText">Vyvahaara Endarenu, Voice Of H H Satchidaanandendra Saraswathi Swamiji Of Holenarasipur</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/D_j18JUvWOc/Sampradaya Endarenu  Voice Of H H Satchidanandendra Saraswathi Swamiji"><img src="<?=PUBLIC_URL?>images/stock/video-covers/012.jpg" alt="Sampradaya Endarenu  Voice Of H H Satchidanandendra Saraswathi Swamiji" /><p class="sideBarText">Sampradaya Endarenu  Voice Of H H Satchidanandendra Saraswathi Swamiji</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/IkYNSYQBcqI/Sadguru Charanake Baagi"><img src="<?=PUBLIC_URL?>images/stock/video-covers/013.jpg" alt="Sadguru Charanake Baagi" /><p class="sideBarText">Sadguru Charanake Baagi</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/YCI9csGcOxQ/Hare Rama Hare Swamiji Song"><img src="<?=PUBLIC_URL?>images/stock/video-covers/014.jpg" alt="Hare Rama Hare Swamiji Song" /><p class="sideBarText">Hare Rama Hare Swamiji Song</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/fefmkoMQBcw/S Putta Shamanna Voice"><img src="<?=PUBLIC_URL?>images/stock/video-covers/015.jpg" alt="S Putta Shamanna Voice" /><p class="sideBarText">S Putta Shamanna Voice</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/eHygejqZyPk/Upanishat Endarenu H H Sawamiji"><img src="<?=PUBLIC_URL?>images/stock/video-covers/016.jpg" alt="Upanishat Endarenu H H Sawamiji" /><p class="sideBarText">Upanishat Endarenu H H Sawamiji</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/YOBW5cQs4wM/Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 03"><img src="<?=PUBLIC_URL?>images/stock/video-covers/017.jpg" alt="Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 03" /><p class="sideBarText">Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 03</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/PKHcE37xBQc/Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 02"><img src="<?=PUBLIC_URL?>images/stock/video-covers/018.jpg" alt="Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 02" /><p class="sideBarText">Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 02</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/ANRc2MuiqrI/Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 01"><img src="<?=PUBLIC_URL?>images/stock/video-covers/019.jpg" alt="Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 01" /><p class="sideBarText">Mahamahopadhyaya Dr. K.g.subraya Sharma Vardhanthi Utsava Part 01</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/RoDmoDqaqhY/Soundarya Lahari In 100 Raaga's"><img src="<?=PUBLIC_URL?>images/stock/video-covers/020.jpg" alt="Soundarya Lahari In 100 Raaga's" /><p class="sideBarText">Soundarya Lahari In 100 Raaga's</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/7pt-xfoPesg/Satyave Gedditu Song  Real Independence Day"><img src="<?=PUBLIC_URL?>images/stock/video-covers/021.jpg" alt="Satyave Gedditu Song  Real Independence Day" /><p class="sideBarText">Satyave Gedditu Song  Real Independence Day</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/pYHCLaNRBgc/Ishavasya Upanishad Sara In Kaannada Upanyasa By Dr K G Subraya Sharma"><img src="<?=PUBLIC_URL?>images/stock/video-covers/022.jpg" alt="Ishavasya Upanishad Sara In Kaannada Upanyasa By Dr K G Subraya Sharma" /><p class="sideBarText">Ishavasya Upanishad Sara In Kaannada Upanyasa By Dr K G Subraya Sharma</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/NR8iwkhLtZU/Dashopanishat Teaching For Learners"><img src="<?=PUBLIC_URL?>images/stock/video-covers/023.jpg" alt="Dashopanishat Teaching For Learners" /><p class="sideBarText">Dashopanishat Teaching For Learners</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/jNxLLnC3F6o/Dashopanishat Main Mantras Teaching 0001"><img src="<?=PUBLIC_URL?>images/stock/video-covers/024.jpg" alt="Dashopanishat Main Mantras Teaching 0001" /><p class="sideBarText">Dashopanishat Main Mantras Teaching 0001</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/rpuNPsu_anU/Kannada Lecture On Vyasa Purnima &amp; Guru Ashtaka Of Shankaracharya, By Dr K G Subraya Sharma"><img src="<?=PUBLIC_URL?>images/stock/video-covers/025.jpg" alt="Kannada Lecture On Vyasa Purnima &amp; Guru Ashtaka Of Shankaracharya, By Dr K G Subraya Sharma" /><p class="sideBarText">Kannada Lecture On Vyasa Purnima &amp; Guru Ashtaka Of Shankaracharya, By Dr K G Subraya Sharma</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/I4j1kYqOhcM/Viveka Choodamani Upanyasa By Mahamahopaadhyaaya Dr K.g.subraya Sharmaji In   Kannada"><img src="<?=PUBLIC_URL?>images/stock/video-covers/026.jpg" alt="Viveka Choodamani Upanyasa By Mahamahopaadhyaaya Dr K.g.subraya Sharmaji In   Kannada" /><p class="sideBarText">Viveka Choodamani Upanyasa By Mahamahopaadhyaaya Dr K.g.subraya Sharmaji In   Kannada</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/kMtnEAqIB1g/Viveka In Taittireeya"><img src="<?=PUBLIC_URL?>images/stock/video-covers/027.jpg" alt="Viveka In Taittireeya" /><p class="sideBarText">Viveka In Taittireeya</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/OxF_3Ian7Xo/Janivaarada Mahatva Dr K G Subraya Sharma"><img src="<?=PUBLIC_URL?>images/stock/video-covers/028.jpg" alt="Janivaarada Mahatva Dr K G Subraya Sharma" /><p class="sideBarText">Janivaarada Mahatva Dr K G Subraya Sharma</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/HiJuSkYYoag/ನಮಗೆ ಇಂದು ವೇದಾಂತ ಬೇಕೇ ? Vol - 2  ಅಂದರೆ -  ಇಂದು ವೇದಾಂತ ಬೇಕೇ?, ಕೇಳಿ........ ನೀವೇ ಉತ್ತರ ಕಂಡು ಹಿಡಿಯಿರಿ."><img src="<?=PUBLIC_URL?>images/stock/video-covers/029.jpg" alt="ನಮಗೆ ಇಂದು ವೇದಾಂತ ಬೇಕೇ ? Vol - 2  ಅಂದರೆ -  ಇಂದು ವೇದಾಂತ ಬೇಕೇ?, ಕೇಳಿ........ ನೀವೇ ಉತ್ತರ ಕಂಡು ಹಿಡಿಯಿರಿ." /><p class="sideBarText">ನಮಗೆ ಇಂದು ವೇದಾಂತ ಬೇಕೇ ? Vol - 2  ಅಂದರೆ -  ಇಂದು ವೇದಾಂತ ಬೇಕೇ?, ಕೇಳಿ........ ನೀವೇ ಉತ್ತರ ಕಂಡು ಹಿಡಿಯಿರಿ.</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/MCWysMOAPg8/Namage Indu Vedaantha Beke ? ನಮಗೆ ಇಂದು ವೇದಾಂತ ಬೇಕೇ ? Vol.-1"><img src="<?=PUBLIC_URL?>images/stock/video-covers/030.jpg" alt="Namage Indu Vedaantha Beke ? ನಮಗೆ ಇಂದು ವೇದಾಂತ ಬೇಕೇ ? Vol.-1" /><p class="sideBarText">Namage Indu Vedaantha Beke ? ನಮಗೆ ಇಂದು ವೇದಾಂತ ಬೇಕೇ ? Vol.-1</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/0GXKfaNS6jY/Brahmakkoo Ninagoo Bhedavilla"><img src="<?=PUBLIC_URL?>images/stock/video-covers/031.jpg" alt="Brahmakkoo Ninagoo Bhedavilla" /><p class="sideBarText">Brahmakkoo Ninagoo Bhedavilla</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/PwkVg3oX3QI/Dhanya Naanaadenu"><img src="<?=PUBLIC_URL?>images/stock/video-covers/032.jpg" alt="Dhanya Naanaadenu" /><p class="sideBarText">Dhanya Naanaadenu</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/V9C9P1lgVOI/Mayapaashada Bandhade Baride"><img src="<?=PUBLIC_URL?>images/stock/video-covers/033.jpg" alt="Mayapaashada Bandhade Baride" /><p class="sideBarText">Mayapaashada Bandhade Baride</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/wEn2GBUKrlg/Rama Rama Rama Enniri"><img src="<?=PUBLIC_URL?>images/stock/video-covers/034.jpg" alt="Rama Rama Rama Enniri" /><p class="sideBarText">Rama Rama Rama Enniri</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/UVF1bNRTB30/Mandukya Upanishad Sara In Kannada"><img src="<?=PUBLIC_URL?>images/stock/video-covers/035.jpg" alt="Mandukya Upanishad Sara In Kannada" /><p class="sideBarText">Mandukya Upanishad Sara In Kannada</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/b-4l-Cu5tKk/Shrimad Bhagavdgita Lecture In English By Dr.k.g.subraya Sharmaji At Iiwc"><img src="<?=PUBLIC_URL?>images/stock/video-covers/036.jpg" alt="Shrimad Bhagavdgita Lecture In English By Dr.k.g.subraya Sharmaji At Iiwc" /><p class="sideBarText">Shrimad Bhagavdgita Lecture In English By Dr.k.g.subraya Sharmaji At Iiwc</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/YwlYqf0VmLQ/Sri Srigala Aaradhane Kannada  Shankara"><img src="<?=PUBLIC_URL?>images/stock/video-covers/037.jpg" alt="Sri Srigala Aaradhane Kannada  Shankara" /><p class="sideBarText">Sri Srigala Aaradhane Kannada  Shankara</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/UQxfzn7Xvwk/Shankara Hridayam, Sanskrit Lecture By Mahamahopaadhyaya Dr K G Subraya Sharma 0001"><img src="<?=PUBLIC_URL?>images/stock/video-covers/038.jpg" alt="Shankara Hridayam, Sanskrit Lecture By Mahamahopaadhyaya Dr K G Subraya Sharma 0001" /><p class="sideBarText">Shankara Hridayam, Sanskrit Lecture By Mahamahopaadhyaya Dr K G Subraya Sharma 0001</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/peCdOBRQLKI/Jist Of Shantimantras In English By Mahamahopadhyaya Dr.k.g.subraya Sharmaji"><img src="<?=PUBLIC_URL?>images/stock/video-covers/039.jpg" alt="Jist Of Shantimantras In English By Mahamahopadhyaya Dr.k.g.subraya Sharmaji" /><p class="sideBarText">Jist Of Shantimantras In English By Mahamahopadhyaya Dr.k.g.subraya Sharmaji</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/Ly8zu-Ck6UA/N H S Prayer"><img src="<?=PUBLIC_URL?>images/stock/video-covers/040.jpg" alt="N H S Prayer" /><p class="sideBarText">N H S Prayer</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/0rMVSYYxfO8/Mandookya Rahasya Vivruthihi"><img src="<?=PUBLIC_URL?>images/stock/video-covers/041.jpg" alt="Mandookya Rahasya Vivruthihi" /><p class="sideBarText">Mandookya Rahasya Vivruthihi</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/x_vZP2CbKvI/Bhagavadgeetha  Yaarige ? (saara)  Upanyasa K G Subraya Sharmaji"><img src="<?=PUBLIC_URL?>images/stock/video-covers/042.jpg" alt="Bhagavadgeetha  Yaarige ? (saara)  Upanyasa K G Subraya Sharmaji" /><p class="sideBarText">Bhagavadgeetha  Yaarige ? (saara)  Upanyasa K G Subraya Sharmaji</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/kCV_WHVgY80/Aatmahatye Endarenu ? H H Satchidaanandendra Saraswathi Of Holenarasipur Lecture"><img src="<?=PUBLIC_URL?>images/stock/video-covers/043.jpg" alt="Aatmahatye Endarenu ? H H Satchidaanandendra Saraswathi Of Holenarasipur Lecture" /><p class="sideBarText">Aatmahatye Endarenu ? H H Satchidaanandendra Saraswathi Of Holenarasipur Lecture</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/4N3Lwx2KoyU/Avasthatraya Prakriya By Dr.k.g.subraya Sharmaji"><img src="<?=PUBLIC_URL?>images/stock/video-covers/044.jpg" alt="Avasthatraya Prakriya By Dr.k.g.subraya Sharmaji" /><p class="sideBarText">Avasthatraya Prakriya By Dr.k.g.subraya Sharmaji</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/bT6Kl_kpnV0/5 Mundakopanishat Saara"><img src="<?=PUBLIC_URL?>images/stock/video-covers/045.jpg" alt="5 Mundakopanishat Saara" /><p class="sideBarText">5 Mundakopanishat Saara</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/uDxj03l9NT0/7 Aitareya Upanishat Saara"><img src="<?=PUBLIC_URL?>images/stock/video-covers/046.jpg" alt="7 Aitareya Upanishat Saara" /><p class="sideBarText">7 Aitareya Upanishat Saara</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/CCa4FvVv2gk/4 Prashnopanishat Saara"><img src="<?=PUBLIC_URL?>images/stock/video-covers/047.jpg" alt="4 Prashnopanishat Saara" /><p class="sideBarText">4 Prashnopanishat Saara</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/O83kF5VBFgo/3 Kathopanishat Saara Kannada Lecture"><img src="<?=PUBLIC_URL?>images/stock/video-covers/048.jpg" alt="3 Kathopanishat Saara Kannada Lecture" /><p class="sideBarText">3 Kathopanishat Saara Kannada Lecture</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/9zEDi6ClkBU/Vyasa Poornima"><img src="<?=PUBLIC_URL?>images/stock/video-covers/049.jpg" alt="Vyasa Poornima" /><p class="sideBarText">Vyasa Poornima</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/Sm6maQCOYTY/Bhagavatpaada Shankaracharya"><img src="<?=PUBLIC_URL?>images/stock/video-covers/050.jpg" alt="Bhagavatpaada Shankaracharya" /><p class="sideBarText">Bhagavatpaada Shankaracharya</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/kjxIJ1lMmJE/Vedantha Darshana"><img src="<?=PUBLIC_URL?>images/stock/video-covers/051.jpg" alt="Vedantha Darshana" /><p class="sideBarText">Vedantha Darshana</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/ziTLaVZMzH4/Mayapaashada"><img src="<?=PUBLIC_URL?>images/stock/video-covers/052.jpg" alt="Mayapaashada" /><p class="sideBarText">Mayapaashada</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/k1kJiex-VZg/Elu Jeevara Jeeva"><img src="<?=PUBLIC_URL?>images/stock/video-covers/053.jpg" alt="Elu Jeevara Jeeva" /><p class="sideBarText">Elu Jeevara Jeeva</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/osCOWZDVA9s/2 Kenopanishat  Saara, ಕೇನೋಪನಿಶತ್ ಉಪನ್ಯಾಸ"><img src="<?=PUBLIC_URL?>images/stock/video-covers/054.jpg" alt="2 Kenopanishat  Saara, ಕೇನೋಪನಿಶತ್ ಉಪನ್ಯಾಸ" /><p class="sideBarText">2 Kenopanishat  Saara, ಕೇನೋಪನಿಶತ್ ಉಪನ್ಯಾಸ</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/hRY8MAY9pNc/1 Eeshavaasya Upanishat Saara"><img src="<?=PUBLIC_URL?>images/stock/video-covers/055.jpg" alt="1 Eeshavaasya Upanishat Saara" /><p class="sideBarText">1 Eeshavaasya Upanishat Saara</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/nZ0JFCvfxTM/Rama Rama Rama  Enniri"><img src="<?=PUBLIC_URL?>images/stock/video-covers/056.jpg" alt="Rama Rama Rama  Enniri" /><p class="sideBarText">Rama Rama Rama  Enniri</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/ENECw2RnWFk/Kaalanaatavaa Nodi"><img src="<?=PUBLIC_URL?>images/stock/video-covers/057.jpg" alt="Kaalanaatavaa Nodi" /><p class="sideBarText">Kaalanaatavaa Nodi</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/NRWt-B-Byfw/Adhyaaropaapavada Prakriya Upanyasa In Sanskrit By Mahaamahopaadhyaya Dr.k.g.subraya Sharmaji,"><img src="<?=PUBLIC_URL?>images/stock/video-covers/058.jpg" alt="Adhyaaropaapavada Prakriya Upanyasa In Sanskrit By Mahaamahopaadhyaya Dr.k.g.subraya Sharmaji," /><p class="sideBarText">Adhyaaropaapavada Prakriya Upanyasa In Sanskrit By Mahaamahopaadhyaya Dr.k.g.subraya Sharmaji,</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/iOjlPhHQXVg/Karunisute Nee Kaaye"><img src="<?=PUBLIC_URL?>images/stock/video-covers/059.jpg" alt="Karunisute Nee Kaaye" /><p class="sideBarText">Karunisute Nee Kaaye</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/wEIKJRLQLxc/Nodutaliruvenu Naanellaa 0002"><img src="<?=PUBLIC_URL?>images/stock/video-covers/060.jpg" alt="Nodutaliruvenu Naanellaa 0002" /><p class="sideBarText">Nodutaliruvenu Naanellaa 0002</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/sMwwPeek2RM/Naane Brahmavu Berallaa"><img src="<?=PUBLIC_URL?>images/stock/video-covers/061.jpg" alt="Naane Brahmavu Berallaa" /><p class="sideBarText">Naane Brahmavu Berallaa</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/a3X1kjpnKZg/Anjaneya Vandipenayya"><img src="<?=PUBLIC_URL?>images/stock/video-covers/062.jpg" alt="Anjaneya Vandipenayya" /><p class="sideBarText">Anjaneya Vandipenayya</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/eOjxkR3nHH4/Banniri Bhajaneya Maadona"><img src="<?=PUBLIC_URL?>images/stock/video-covers/063.jpg" alt="Banniri Bhajaneya Maadona" /><p class="sideBarText">Banniri Bhajaneya Maadona</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/DCyMf1Nskcg/K Subramanya Shastriji - Poulastya Brahmana Drama"><img src="<?=PUBLIC_URL?>images/stock/video-covers/064.jpg" alt="K Subramanya Shastriji - Poulastya Brahmana Drama" /><p class="sideBarText">K Subramanya Shastriji - Poulastya Brahmana Drama</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/wFXmojxoJq0/Sharanu Shankara 0001"><img src="<?=PUBLIC_URL?>images/stock/video-covers/065.jpg" alt="Sharanu Shankara 0001" /><p class="sideBarText">Sharanu Shankara 0001</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/-NcCpzF0FbE/Shiva Shiva  Song"><img src="<?=PUBLIC_URL?>images/stock/video-covers/066.jpg" alt="Shiva Shiva  Song" /><p class="sideBarText">Shiva Shiva  Song</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/0azekaWGj0Y/Sooryanamaskaara Mantra- Ratha Saptami,"><img src="<?=PUBLIC_URL?>images/stock/video-covers/067.jpg" alt="Sooryanamaskaara Mantra- Ratha Saptami," /><p class="sideBarText">Sooryanamaskaara Mantra- Ratha Saptami,</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/oHpQCc0GWHQ/Sullina Jagavidu  Sung By Sanjeeva Murthy"><img src="<?=PUBLIC_URL?>images/stock/video-covers/068.jpg" alt="Sullina Jagavidu  Sung By Sanjeeva Murthy" /><p class="sideBarText">Sullina Jagavidu  Sung By Sanjeeva Murthy</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/MjdGyPC_S6Y/Sadguru Charanake Sanjeeva Murthy"><img src="<?=PUBLIC_URL?>images/stock/video-covers/069.jpg" alt="Sadguru Charanake Sanjeeva Murthy" /><p class="sideBarText">Sadguru Charanake Sanjeeva Murthy</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/s4VGPTQJ-OU/Dayamaado Deva, Sung By  Chitradurga Sanjeeva Murthy"><img src="<?=PUBLIC_URL?>images/stock/video-covers/070.jpg" alt="Dayamaado Deva, Sung By  Chitradurga Sanjeeva Murthy" /><p class="sideBarText">Dayamaado Deva, Sung By  Chitradurga Sanjeeva Murthy</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/7iRqvjve5EE/Nelanolenitho Mandi Gurugalu"><img src="<?=PUBLIC_URL?>images/stock/video-covers/071.jpg" alt="Nelanolenitho Mandi Gurugalu" /><p class="sideBarText">Nelanolenitho Mandi Gurugalu</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/K85xd30wtyQ/Sakkadave Bekemba"><img src="<?=PUBLIC_URL?>images/stock/video-covers/072.jpg" alt="Sakkadave Bekemba" /><p class="sideBarText">Sakkadave Bekemba</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/RJQqjvcGqRg/Ganesha Song With Vedanta By Sri. K.subramanya Shastry"><img src="<?=PUBLIC_URL?>images/stock/video-covers/073.jpg" alt="Ganesha Song With Vedanta By Sri. K.subramanya Shastry" /><p class="sideBarText">Ganesha Song With Vedanta By Sri. K.subramanya Shastry</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/Fy0ZzlQmebY/6 Maandukya Upanishat"><img src="<?=PUBLIC_URL?>images/stock/video-covers/074.jpg" alt="6 Maandukya Upanishat" /><p class="sideBarText">6 Maandukya Upanishat</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/Q7ukl4eBuPw/Naada Naada - Sung By Sanjeeva Murthy"><img src="<?=PUBLIC_URL?>images/stock/video-covers/075.jpg" alt="Naada Naada - Sung By Sanjeeva Murthy" /><p class="sideBarText">Naada Naada - Sung By Sanjeeva Murthy</p></a></div>
				<div class="col-md-10"><a href="<?=BASE_URL?>pravachana/videoPlayer/ERgKn8s7RFQ/Naada Sung by Sanjeeva Murthy 3 Gelavu , Biduvanendige"><img src="<?=PUBLIC_URL?>images/stock/video-covers/076.jpg" alt="Naada Sung by Sanjeeva Murthy 3 Gelavu , Biduvanendige" /><p class="sideBarText">Naada Sung by Sanjeeva Murthy 3 Gelavu , Biduvanendige</p></a></div>
			</div>
		</div>
	</div>
</div>
</div>
