  <div class="container main">
    <h2 class="clear-margins">ಪುಸ್ತಕ ಬಿಡುಗಡೆ ಸಮಾರಂಭಗಳು</h2><br />
    <div class="row albumPhotos"  id="imageview">
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0003.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0003.jpg" alt="`ನ ಹಿ ಜ್ಞಾನೇನ ಸದೃಶಂ' - 25 (ಪುನರ್ಮುದ್ರಣ) ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ; ಶ್ರೀಯುತರಾದ ಪಿ. ಆರ್. ಶಿವಶಂಕರ್, ಬಿ. ಎ. ಮಂಜುನಾಥ್, ಟಿ. ಕೆ. ರಾಮನಾರಾಯಣ, ಟಿ. ಕೆ. ಬದರೀನಾಥ್ ; 23-8-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0004.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0004.jpg" alt="`ಮಕ್ಕಳಿಗಾಗಿ ಸ್ತೋತ್ರಗಳು' - 75 ಕೃತಿಯ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ; 16-7-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0005.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0005.jpg" alt="`ನ ಹಿ ಜ್ಞಾನೇನ ಸದೃಶಂ' - 25 (ದ್ವಿತೀಯ ಮುದ್ರಣ) ಗ್ರಂಥವನ್ನು ಲೋಕಾರ್ಪಣ ಮಾಡಿ ಅನಂತರ ಶ್ರೀಯುತ ಪಿ. ಆರ್. ಶಿವಶಂಕರ್ ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 23-8-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0006.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0006.jpg" alt="`ಜೀವನ್ಮುಕ್ತ ಚತುಷ್ಟಯ'-13 (ಪುನರ್ಮುದ್ರಿತ) ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಂದು ಶ್ರೀ ಎನ್. ನಂದಕುಮಾರ್ ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 24-6-2016, ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0022.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0022.jpg" alt="ತಮ್ಮ ಪುತ್ರಿಯರಾದ ಕುಮಾರೀ ಸೀತಾ ಮತ್ತು ಕುಮಾರೀ ಪ್ರೀತಿಯರೊಂದಿಗೆ ಶ್ರೀಮತಿ ರಾಜೇಶ್ವರೀಶರ್ಮಾ ಮತ್ತು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0023.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0023.jpg" alt="`ವೇದಾಂತವಾರಿಧಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಗೀತಾಕಲ್ಪತರು - 40' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 17-8-2013, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0024.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0024.jpg" alt="`ಅದ್ವೈತವೇದಾಂತಸವ್ಯಸಾಚಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶಂಕರಜಯಂತೀ' - ಎಂಬ ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭ - 25-8-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0025.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0025.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶ್ರೀರಮಣಸುಧಾ' ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಗಣ್ಯ ಅತಿಥಿಗಳು - 20-4-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0026.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0026.jpg" alt="ಮಹಾಮಹೋಪಾಧ್ಯಾಯ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ ಔಪನಿಷದ ಪುರುಷ - 43 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು, 26-11-2013, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0028.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0028.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ತಸ್ಮೈ ಶ್ರೀಗುರವೇ ನಮಃ' - 67 ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಯುತರಾದ ಡಾ ॥ ಸಪ್ನಾ, ಎಸ್. ಶ್ರೀಹರಿ, ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿಗಳು; ಯು. ಹೆಚ್. ಸುಬ್ರಹ್ಮಣ್ಯಂರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 20-11-2015 ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0029.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0029.jpg" alt="ಗೀತೋಪನಿಷತ್'-68 ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು ಮತ್ತು ಶ್ರೀಮತಿ ರುಕ್ಮಿಣಿ ರಾಮು (USA), ಡಾ ॥ ಡಿ. ಸಿ. ರಾವ್ (USA), ಡಾ ॥ ವಿಜಯೇಂದ್ರ ಮುನಿಕೋಟಿ (ಜರ್ಮನಿ), ಡಾ ॥ ಸುಂದರರಾಮನ್, 31-12-2015, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0030.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0030.jpg" alt="ಶ್ರೀ ಶರ್ಮರ `ಸುಭಾಷಿತ ಸಂವತ್ಸರ' ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಯುತರಾದ ಪ್ರೊ  ॥ ರಾಮಚಂದ್ರ ಅತ್ತಿಗನಾಳ್, ಎನ್. ಕಾರ್ತಿಕೇಯನ್, ಡಾ ॥ ಅನಸೂಯಾ ಎಸ್. ರಾಜೀವ್, ಶ್ರೀ ಸಿ. ಎ. ಸಂಜೀವಮೂರ್ತಿಗಳು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 28-11-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0031.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0031.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾಜಿಯವರ `ಪ್ರಸ್ಥಾನತ್ರಯಂ' - 69 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಟಿ. ಕೆ. ತಿಮ್ಮರಾಜಶೆಟ್ಟಿ, ಬಿ. ಎನ್. ರಂಗಣ್ಣ, ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು (USA), ಸಿ. ಕೆ. ಸುಬ್ಬನರಸಿಂಹ, ವಿ. ರಾಜಣ್ಣ; 20-1-2016 ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0033.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0033.jpg" alt="ಗೀತೋಪನಿಷತ್'-68 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಯುತರಾದ ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು (USA), ಶ್ರೀಮತಿ ರುಕ್ಮಿಣಿ ರಾಮು (USA), ಡಾ ॥ ಡಿ. ಸಿ. ರಾವ್ (USA), ಡಾ ॥ ವಿಜಯೇಂದ್ರ ಮುನಿಕೋಟಿ (ಜರ್ಮನಿ), ಡಾ ॥ ಸುಂದರಾಜನ್, 31-12-2015, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0034.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0034.jpg" alt="`ಗೀತೋಪನಿಷತ್'-68 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು, ಶ್ರೀಮತಿ ರುಕ್ಮಿಣಿ ರಾಮು (USA), ಡಾ ॥ ಡಿ. ಸಿ. ರಾವ್ (USA), ಡಾ ॥ ವಿಜಯೇಂದ್ರ ಮುನಿಕೋಟಿ (ಜರ್ಮನಿ), ಶ್ರೀ ಸಿ. ಎ. ಸಂಜೀವಮೂರ್ತಿಗಳು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 31-12-2015, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0035.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0035.jpg" alt="12-07-2010 ಸೋಮವಾರದಂದು 'ವೇದಾಂತನಿಲಯ'ದಲ್ಲಿ ಮಹಾಮಹೋಪಾಧ್ಯಾಯ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ 'ಶಿವರಾತ್ರಿ' ಕೃತಿಯ ಬಿಡುಗಡೆಯ ಸಮಾರಂಭ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0037.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0037.jpg" alt="25-07-2010 ಭಾನುವಾರ 'ಗುರುಪೂರ್ಣಿಮೆ'ಯಂದು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ಮತ್ತು ಶ್ರೀಮತಿ ಎಸ್. ರಾಜೇಶ್ವರೀಶರ್ಮಾ-ದಂಪತಿಗಳಿಂದ ಸದ್ಗುರುಪೂಜೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0038.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0038.jpg" alt="ಶ್ರೀಮತಿ ಎಸ್. ರಾಜೇಶ್ವರೀಶರ್ಮಾ ಮತ್ತು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ಆದರ್ಶ ದಂಪತಿಗಳು ಶ್ರೀಶಂಕರಾಚಾರ್ಯರ ಹಾಗೂ ಶ್ರೀಸದ್ಗುರುಗಳ ಕೃಪಾಶ್ರಯದ ಅಡಿಯಲ್ಲಿ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0039.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0039.jpg" alt="ಅಧ್ಯಾತ್ಮವಿದ್ಯಾಪ್ರವೀಣ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ಉಪದೇಶಸಿಂಚನಂ' ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ 10-6-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0040.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0040.jpg" alt="ವೇದಾಂತಚಕ್ರವರ್ತಿ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಸಂದೇಶಾಮೃತ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭ 20-10-2012, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0041.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0041.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶಂಕರ Ph.D.' ಗ್ರಂಥವನ್ನು ಕರ್ನಾಟಕ ಸಂಸ್ಕೃತ ವಿಶ್ವವಿದ್ಯಾಲಯದ ಸನ್ಮಾನ್ಯ ಕುಲಪತಿಗಳಾದ ಗೌರವಾನ್ವಿತ ಪ್ರೊ  ॥ ಮಲ್ಲೇಪುರಂ ಜಿ. ವೆಂಕಟೇಶರವರು ಲೋಕಾರ್ಪಣೆ ಮಾಡುತ್ತಿರುವುದು - ಸೋಮವಾರ, 28-1-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0042.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0042.jpg" alt="ವೇದಾಂತಕಾಮಧೇನು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಜನ್ಮಾಂತರ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 18-7-2013, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0043.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0043.jpg" alt="16-8-2010 ಸೋಮವಾರದಂದು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ನವೋಪನಿಷದಃ' ಗ್ರಂಥದ ಬಿಡುಗಡೆಯ ಸಮಾರಂಭ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0045.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0045.jpg" alt="30-10-2010 ರಂದು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ಶಾಂತಿಮಂತ್ರಗಳು' ಕೃತಿಯ ಲೋಕಾರ್ಪಣೆಯ ಸಮಾರಂಭದಲ್ಲಿ ಮುಮುಕ್ಷು ಶ್ರೋತೃಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0052.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0052.jpg" alt="03-12-2010 ರಂದು ವೇದಾಂತಪ್ರಭಾಕರ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ 'vedamahime' ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಉಪಸ್ಥಿತರಾಗಿರುವ ವೇದಾಭಿಮಾನಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0053.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0053.jpg" alt="31-12-2010 ರಂದು ಮಹಾಮಹೋಪಾಧ್ಯಾಯ ವೇ।। ಬ್ರ।। ಶ್ರೀ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ 'Prabodha Chintamani' ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಜಿಜ್ಞಾಸುಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0055.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0055.jpg" alt="30-10-2010 ಶನಿವಾರದಂದು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ 'ಶಾಂತಿಮಂತ್ರಗಳು' ಕೃತಿಯ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0056.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0056.jpg" alt="16-08-2010 ರಂದು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ 'ನವೋಪನಿಷದಃ' ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೋತೃ ಜಿಜ್ಞಾಸುಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0059.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0059.jpg" alt="`ಪ್ರಸ್ಥಾನತ್ರಯಂ'-69 ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಅತಿಥಿಗಳು. 20-1-2016, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0060.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0060.jpg" alt="`ಸುಭಾಷಿತ ಸಂವತ್ಸರ' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀ ಎನ್. ಕಾರ್ತಿಕೇಯನ್‍ರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 28-11-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0061.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0061.jpg" alt="`ವೇದಾಂಗಗಳು'-72 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಮತಿ ಪ್ರೊ  ॥ ಎನ್. ನಾಗರತ್ನಾರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 19-4-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0062.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0062.jpg" alt="`ನನ್ನ ಗುರುಕುಲವಾಸ'-71 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಯುತ ಕೆ. ಎಂ. ಶ್ರೀನಿವಾಸ ಭಟ್ಟರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 12-3-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0063.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0063.jpg" alt="`ಸುಭಾಷಿತ ಸಂವತ್ಸರ' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಎನ್. ಕಾರ್ತಿಕೇಯನ್ ರವರಿಗೆ ಪ್ರೀತಿಪೂರ್ವಕ ಸನ್ಮಾನ. 28-11-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0064.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0064.jpg" alt="`ತಸ್ಮೈ ಶ್ರೀಗುರವೇ ನಮಃ'- 67 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿಗಳು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 20-11-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0065.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0065.jpg" alt="`ಸುಭಾಷಿತ ಸಂವತ್ಸರ' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ 28-11-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0066.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0066.jpg" alt="`ಪ್ರಥಮ ಪುಸ್ತಕಂ'-70 ಕೃತಿರತ್ನದ ಬಿಡುಗಡೆ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಯುತ ಎಂ. ಎಸ್. ಕೃಷ್ಣಮೂರ್ತಿಗಳಿಗೆ ಸನ್ಮಾನ. 16-2-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0067.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0067.jpg" alt="ಅದ್ವೈತಜ್ಞಾನಸಿಂಧು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ 'ಆರಾಧನ ಸಂದೇಶ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ (21-03-2012)" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0071.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0071.jpg" alt="`ಶತಕತ್ರಯಸಾರ'-87 ಕೃತಿರತ್ನದ ಬಿಡುಗಡೆಯ ಸಮಾರಂಭ; 25-7-2017, ಮಂಗಳವಾರ ; ಪ್ರೊ  ॥ ಟಿ. ಅಶ್ವತ್ಥನಾರಾಯಣರಾವ್, ಶ್ರೀ ಎಂ. ಎಸ್. ಕೃಷ್ಣಮೂರ್ತಿ, ಶ್ರೀ ವರದರಾಜ ಬೆಳವಾಡಿ (USA) ಶ್ರೀ ಮತ್ತೂರು ಹರಿನಾರಾಯಣರೊಂದಿಗೆ ಲೇಖಕ ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0072.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0072.jpg" alt="ವೇದಾಂತಡಿಂಡಿಮಸಾರ'-86 ಕೃತಿರತ್ನದ ಬಿಡುಗಡೆಯ ಸಮಾರಂಭದಲ್ಲಿ ಶಾಂಕರಭಾಷ್ಯ ಪ್ರವಚನ ಶ್ರೋತೃಗಳಾದ ವೇದಾಂತಾಭಿಮಾನಿಗಳು; 29-6-2017, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0073.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0073.jpg" alt="`ವೇದಾಂತಡಿಂಡಿಮಸಾರ'-86; ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ; 29-6-2017, ಗುರುವಾರ ವಿದ್ವಾನ್ ಕೆ. ಪಿ. ರತ್ನಾಕರಭಟ್ಟರು, ಶ್ರೀ ವೈ. ಎಸ್. ಸುಬ್ರಹ್ಮಣ್ಯ, ಶ್ರೀ ಪಿ. ಆರ್. ಶಿವಶಂಕರ್, ಶ್ರೀ ಎಸ್. ಶ್ರೀಹರಿ - ಇವರೊಂದಿಗೆ ಲೇಖಕ ಡಾ ॥ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0074.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0074.jpg" alt="ಶತಕತ್ರಯಸಾರ'-87; ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣೆ; 25-7-2017, ಮಂಗಳವಾರ; ಶಾಂಕರಭಾಷ್ಯ ಪಾಠಪ್ರವಚದ ಶ್ರೋತೃಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0075.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0075.jpg" alt="ಶಾಂಕರಬೋಧಾಮೃತಂ'-84 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ; 27-4-2017, ಗುರುವಾರ ಸನ್ಮಾನ್ಯರಾದ ಸಚ್ಚಿದಾನಂದಮೂರ್ತಿ, ಎಂ. ಎಸ್. ಕೃಷ್ಣಮೂರ್ತಿ, ಬಿ. ಜಿ. ನಾಗರಾಜ, ಕೆ. ವಿನಯ್ ಇವರೊಂದಿಗೆ ಲೇಖಕ ಡಾ ॥ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0076.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0076.jpg" alt="`ಶ್ರೀ ಸುರೇಶ್ವರರ ಸಿಂಹಗರ್ಜನೆ'-79 ಕೃತಿರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣೆಗೊಳಿಸಿದ ನಂತರ ಶ್ರೀ ಎಂ. ಎಸ್. ಕೃಷ್ಣಮೂರ್ತಿಗಳು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 29-11-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0077.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0077.jpg" alt="`ಶಾಂಕರಬೋಧಾಮೃತಂ'-84; ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀ ಬಿ. ಜಿ. ನಾಗರಾಜರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 27-4-2017, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0078.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0078.jpg" alt="`ಶ್ರೀ ಸುರೇಶ್ವರರ ಸಿಂಹಗರ್ಜನೆ'-79; ಬಿಡುಗಡೆಯಂದು ವೇದಾಂತಪ್ರಿಯರು; 29-11-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0079.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0079.jpg" alt="`ಗೀತೆಯಲ್ಲಿ ಗುಣವಿಮರ್ಶೆ'-76 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ 9-8-2016, ಮಂಗಳವಾರ ಶ್ರೀಯುತರಾದ ಸಿ. ಎ. ಸಂಜೀವಮೂರ್ತಿ, ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿ, ಬಿ. ಜಿ. ನಾಗರಾಜ್. ಯು. ಎಚ್. ಸುಬ್ರಹ್ಮಣ್ಯಂ ಅವರು ಇದ್ದಾರೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0080.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0080.jpg" alt="`ಶಂಕರಹೃದಯಂ'-74 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀ ಎಸ್. ರಾಮಚಂದ್ರ ಅಯ್ಯರ್ ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ 15-6-2016; ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0081.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0081.jpg" alt="`ಜೀವನ್ಮುಕ್ತ ಚತುಷ್ಟಯ'-13 (ಪುನರ್ಮುದ್ರಣ) ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ: 24-6-2016, ಶುಕ್ರವಾರ;  ಶ್ರೀಯುತರಾದ ಟಿ. ಜಗನ್ನಾಥ್, ಪೂಜ್ಯ ಸದಾನಂದಗಿರಿ, ಶ್ರೀನಿವಾಸ ಗುಪ್ತ, ಎನ್. ನಂದಕುಮಾರ್, ಎಚ್. ಎಸ್. ಸತ್ಯನಾರಾಯಣ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0082.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0082.jpg" alt="`ನ ಹಿ ಜ್ಞಾನೇನ ಸದೃಶಂ'-25 (ಪುನರ್ಮುದ್ರಣ) ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ 23-8-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0083.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0083.jpg" alt="'ಅದ್ವೈತವೇದಾಂತಸವ್ಯಸಾಚಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ 'ಶಂಕರಜಯಂತೀ'-ಎಂಬ ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭ -25-08-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0084.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0084.jpg" alt=" 'ವೇದಾಗಮವಿದ್ಯಾಸಾಗರ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ 108 ಗಂಟೆಗಳ ಪ್ರವಚನಗಳ ಸಿ. ಡಿ. ಲೋಕಾರ್ಪಣ ಸಂದರ್ಭದಲ್ಲಿ ವಿದ್ವಾನ್ ಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಸನ್ಮಾನ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0086.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0086.jpg" alt="ಶ್ರೀಶರ್ಮಾಜಿಯವರ ಗಂಟೆಗಳ 'ಶ್ವೇತಾಶ್ವತರೋಪನಿಷತ್' ಪ್ರವಚನಗಳ ಸಿ. ಡಿ.ಯನ್ನು ಲೋಕಾರ್ಪಣೆಮಾಡಿ, ಬಿ. ಕೆ. ಕುಮಾರ್ ರವರು ಮಾತನಾಡುತ್ತಿರುವುದು-02-09-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0087.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0087.jpg" alt="'ಶಂಕರಜಯಂತೀ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗುರುಗಳಿಂದ ಆಶೀರ್ವಾದ-25-08-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0089.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0089.jpg" alt="ಮಹಾಮಹೋಪಾಧ್ಯಾಯ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರು ಮಾಡಿರುವ 108 ಗಂಟೆಗಳ 'ಶ್ವೇತಾಶ್ವತರೋಪನಿಷತ್' ಪ್ರವಚನಗಳ ಸಿ. ಡಿ. ಬಿಡುಗಡೆ-02-09-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0090.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0090.jpg" alt="'ಭುವಿವೇದಾಂತೈಕಶ್ರೇಷ್ಠರತ್ನ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ 'ಶಂಕರಜಯಂತೀ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೋತೃಗಳು-25-08-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0091.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0091.jpg" alt="ವೇದಾಂತರತ್ನಾಕರ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ 'ಬಾಲರಾಮಾಯಣಂ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭ-27-09-2012 ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0092.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0092.jpg" alt="ಅದ್ವೈತವೇದಾಂತವಾಚಸ್ಪತಿ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ ಸಂದೇಶಾಮೃತ ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತಾಭಿಮಾನಿ ಶ್ರೋತೃಗಳು 20-10-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0094.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0094.jpg" alt="ವೇದಾಂತಸರಸ್ವತೀ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ 'ಸಂದೇಶಾಮೃತ' ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಅಭಿಮಾನಿಗಳಿಂದ ಸನ್ಮಾನ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0095.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0095.jpg" alt="`ಶ್ರೀ ಸುರೇಶ್ವರರ ಸಿಂಹಗರ್ಜನೆ'-79 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ  29-11-2016,  ಮಂಗಳವಾರ; ಶ್ರೀಯುತರಾದ ಎಂ. ಎಸ್. ಕೃಷ್ಣಮೂರ್ತಿ, ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿ, ಡಾ. ಹೆಚ್. ಎಸ್. ಘಳಿಗೆ, ಕೆ. ಎಸ್. ಅನಂತಸ್ವಾಮಿ - ಇವರೊಂದಿಗೆ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0096.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0096.jpg" alt="`ಪಂಚಕ ಪಂಚಕಂ'-88 ಕೃತಿಯನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡಿದ ಅನಂತರ ಸನ್ಮಾನ್ಯರಾದ ಶ್ರೀಚಂದ್ರಶೇಖರ ಕಾಮತ್ ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 23-8-2017, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0097.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0097.jpg" alt="ಉಪಮಾ ಕಾಳಿದಾಸಸ್ಯ'-80; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಕಾವ್ಯನಾಟಕ ಸಾಹಿತ್ಯ ಅಭಿಮಾನಿಗಳು; 31-12-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0098.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0098.jpg" alt="ಪಂಚಕ ಪಂಚಕಂ'-88; ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶಾಂಕರಭಾಷ್ಯ ಪ್ರವಚನ ಶ್ರೋತಗಳಾದ ಅಭಿಮಾನಿಗಳು; 23-8-2017, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0099.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0099.jpg" alt="`ಭುವಿ ವೇದಾಂತೈಕಶ್ರೇಷ್ಠರತ್ನ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ ಕೃತಿರತ್ನ `ವಿಭೂತಿರೂಪಿಕೃಷ್ಣ' ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 20-11-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0100.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0100.jpg" alt="`ವೇದಾಂತಪ್ರಭಾಕರ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಅಧ್ಯಾರೋಪಾಪವಾದ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತತತ್ತ್ವಜಿಜ್ಞಾಸುಗಳು 22-12-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0102.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0102.jpg" alt="5-1-2013 ಶನಿವಾರದಂದು ಪರಮಪೂಜ್ಯ ಶ್ರೀಶ್ರೀಗಳವರ 132 ನೆಯ ಜಯಂತಿ ಉತ್ಸವದಂದು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಂದ ಸದ್ಗುರುಪಾದುಕಾಪೂಜೆ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0103.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0103.jpg" alt="`ಪಂಚಕ ಪಂಚಕಂ'-88 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ 23-8-2017, ಬುಧವಾರ ಶ್ರೀಚಂದ್ರಶೇಖರ ಕಾಮತ್, ಶ್ರೀ ಶಾಂತಾರಾಂ ಕೆ. ಶಾನುಭೋಗ್, ಶ್ರೀ ಹೆಚ್. ಎಸ್. ಗೋಪಾಲಕೃಷ್ಣ, ಶ್ರೀ ಎಂ. ಕೆ. ಶ್ರೀನಿವಾಸ್ - ಇವರೊಂದಿಗೆ ಲೇಖಕ ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0104.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0104.jpg" alt="`ಉಪಮಾ ಕಾಳಿದಾಸಸ್ಯ'-80 ಕೃತಿರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡಿದ ನಂತರ ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು (USA) ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ 31-12-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0105.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0105.jpg" alt="`ಉಪಮಾ ಕಾಳಿದಾಸಸ್ಯ'-80 ; ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ; 31-12-2016, ಶನಿವಾರ ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು (USA), ಡಾ ॥ ಡಿ. ಸಿ. ರಾವ್ (USA), ಶ್ರೀ ಎನ್. ಕಾರ್ತಿಕೇಯನ್, ಶ್ರೀ ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿಗಳೊಂದಿಗೆ ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0106.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0106.jpg" alt="ಶಾಂಕರಬೋಧಾಮೃತಂ'-84; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಭಾಷ್ಯ ಪ್ರವಚನ ಶ್ರೋತೃಗಳಾದ ಶ್ರೀಶಂಕರರ ಭಕ್ತರುಗಳು; 27-4-2017, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0107.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0107.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶಂಕರ Ph.D.' ಗ್ರಂಥವನ್ನು ಕರ್ನಾಟಕ ಸಂಸ್ಕೃತ ವಿಶ್ವವಿದ್ಯಾಲಯದ ಸನ್ಮಾನ್ಯ ಕುಲಪತಿಗಳಾದ ಗೌರವಾನ್ವಿತ ಪ್ರೊ ॥ ಮಲ್ಲೇಪುರಂ ಜಿ. ವೆಂಕಟೇಶರವರು ಲೋಕಾರ್ಪಣೆ ಮಾಡುತ್ತಿರುವುದು - ಸೋಮವಾರ, 28-1-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0108.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0108.jpg" alt="ವೇದಾಂತಪ್ರಭಾಕರ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಗೌಡಪಾದಾಮೃತ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೋತೃಗಳಾದ ವೇದಾಂತಾಭಿಮಾನಿಗಳು - 16-2-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0109.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0109.jpg" alt="ವೇದಾಂತಚಕ್ರವರ್ತಿ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ `ಶಂಕರ Ph.D.' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೋತೃಗಳಿಂದ ಗೌರವಸಮರ್ಪಣೆ - 28-1-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0110.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0110.jpg" alt="`ಅದ್ವೈತವೇದಾಂತಪ್ರತಿಭಾಪ್ರಕಾಶ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ವೇದಾಂತಮಕರಂದ' ಕೃತಿರತ್ನದ ಹಾಗೂ ಈಶಾವಾಸ್ಯೋಪನಿಷತ್ ಭಾಷ್ಯಂ ಪ್ರವಚನದ C.D. M.P.3 ಲೋಕಾರ್ಪಣ ಸಂದರ್ಭದಲ್ಲಿ ಶ್ರೋತೃಗಳು 16-3-2013, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0111.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0111.jpg" alt="ವೇದಾಂತಗಂಗಾಧರ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಗೌಡಪಾದಾಮೃತ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 16-2-2013, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0112.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0112.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ ವೇದಾಂತಮಕರಂದ ಕೃತಿಯ ಹಾಗೂ ಈಶಾವಾಸ್ಯೋಪನಿಷತ್ ಭಾಷ್ಯಂ ಪ್ರವಚನಗಳ C.D. M.P.3 ಬಿಡುಗಡೆಯ ಸಮಾರಂಭದಲ್ಲಿ ವಿದ್ವಾನ್ ಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ವೇದಾಂತಾಭಿಮಾನಿಗಳಿಂದ ಗೌರವಸಮರ್ಪಣೆ - 16-3-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0113.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0113.jpg" alt="`ಪರಿಪೂರ್ಣಮಹನೀಯ-2012' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ವೇದಾಂತಮಕರಂದ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 16-3-13 ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0114.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0114.jpg" alt="ಅಧ್ಯಾತ್ಮವಿದ್ಯಾಪ್ರವೀಣ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶಂಕರ Ph.D.' ಗ್ರಂಥ ರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತಾಭಿಮಾನಿಗಳು - 28-1-2013 ಸೋಮವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0115.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0115.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶ್ರೀರಮಣಸುಧಾ' ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಗಣ್ಯ ಅತಿಥಿಗಳು - 20-4-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0116.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0116.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ವಿಭೂತಿರೂಪಿಕೃಷ್ಣ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ 20-11-2012" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0117.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0117.jpg" alt="`ಶ್ರೀರಮಣಸುಧಾ' ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣಸಂದರ್ಭದಲ್ಲಿ ಲೇಖಕರಾದ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಸನ್ಮಾನ - 20-4-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0118.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0118.jpg" alt="ವೇದಾಂತಚಕ್ರವರ್ತಿ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ ಧರ್ಮ-ವೇದ-ಬ್ರಹ್ಮ ಎಂಬ ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಧರ್ಮವೇದಾಭಿಮನಿಗಳು - 25-5-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0119.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0119.jpg" alt="ಮಹಾಮಹೋಪಾಧ್ಯಾಯ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ ಧರ್ಮ-ವೇದ-ಬ್ರಹ್ಮ ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 25-5-2013 ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0120.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0120.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ವೇದಾಂತಮಕರಂದ' ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣೆಯ ಸಂದರ್ಭದಲ್ಲಿ ಅಧ್ಯಕ್ಷಪೀಠದಿಂದ ಶ್ರೀ ದೇವಕೃಪಾಕರರವರು ಮಾತನಾಡುತ್ತಿರುವುದು  - 16-3-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0121.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0121.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ ಧರ್ಮ-ವೇದ-ಬ್ರಹ್ಮ ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ-25-5-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0122.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0122.jpg" alt="ಶ್ರೀವಿಜಯನಾಮಸಂವತ್ಸರದ ಶ್ರೀಶಂಕರಜಯಂತೀ 15-5-2013 ರಂದು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಂದ ಸದ್ಗುರುಪಾದುಕಾಪೂಜಾ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0123.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0123.jpg" alt="ಅದ್ವೈತವೇದಾಂತಸವ್ಯಸಾಚಿ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಸದ್ಗುರೂಪಾಸನಂ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಗಣ್ಯ ಅತಿಥಿಗಳು - 27-6-2013, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0126.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0126.jpg" alt="ವೇದಾಗಮವಿದ್ಯಾಸಾಗರ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಜನ್ಮಾಂತರ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಂದರ್ಭದಲ್ಲಿ ಶ್ರೋತೃಗಳಾದ ತತ್ತ್ವಜಿಜ್ಞಾಸುಗಳು - 18-7-2013, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0127.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0127.jpg" alt="ವೇದಾಂತಕಾಮಧೇನು ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಜನ್ಮಾಂತರ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 18-7-2013, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0128.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0128.jpg" alt="ಪರಿಪೂರ್ಣಮಹನೀಯ 2012, ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ `ಸದ್ಗುರೂಪಾಸನಂ' ಗ್ರಂಥಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಗೌರವ ಸನ್ಮಾನ, 27-6-2013, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0129.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0129.jpg" alt="ವೇದಾಂತಗಂಗಾಧರ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ, 18-7-2013 ರಂದು `ಜನ್ಮಾಂತರ' ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೋತೃಗಳಿಂದ `ಗೌರವ ಸನ್ಮಾನ'" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0130.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0130.jpg" alt="ಅಧ್ಯಾತ್ಮವಿದ್ಯಾಪ್ರವೀಣ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಸದ್ಗುರೂಪಾಸನಂ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತಾಭಿಮಾನಿಗಳಾದ ಸದ್ಗುರುಭಕ್ತರು - 27-6-2013, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0131.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0131.jpg" alt="ವೇದಾಂತವಾರಿಧಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಗೀತಾಕಲ್ಪತರು-40' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 17-8-2013, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0132.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0132.jpg" alt="ವಿದ್ಯಾವಿಧಿನಿಧಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಮಹರ್ಷಿಗಳು -41' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಭಾಗವಹಿಸಿದ್ದ ಅಭಿಮಾನಿಗಳು - 19-9-2013, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0133.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0133.jpg" alt="`ಗೀತಾಕಲ್ಪತರು-40' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯ ಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಅಭಿಮಾನಿಗಳಿಂದ ಗೌರವಸನ್ಮಾನ - 17-8-2013, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0134.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0134.jpg" alt="ವೇದಾಂತ ನಿಲಯದಲ್ಲಿ ನಡೆಸಿದ ವೇದಾಂತ ಸತ್ಸಂಗ ಕಾರ್ಯಕ್ರಮದಲ್ಲಿ ತತ್ತ್ವಜಿಜ್ಞಾಸು ವೇದಾಂತಾಭಿಮಾನಿಗಳೊಂದಿಗೆ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0135.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0135.jpg" alt="`ವೇದಾಂತರತ್ನ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಮಹರ್ಷಿಗಳು -41' ಕೃತಿರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣಮಾಡುವಾಗ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 19-9-2013, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0136.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0136.jpg" alt="`ವೇದಾಂತ ಸರಸ್ವತಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಗೀತಾಕಲ್ಪತರು-40' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತಾಭಿಮಾನಿಗಳು - 17-8-2013, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0137.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0137.jpg" alt="ಮಹಾಮಹೋಪಾಧ್ಯಾಯ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಮಹರ್ಷಿಗಳು-41' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಅಭಿಮಾನಿಗಳಿಂದ ಗೌರವಸನ್ಮಾನ - 19-9-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0139.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0139.jpg" alt="ವೇದವಿದ್ಯಾಭೂಷಣ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಉಪನಯನಂ-42' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 28-10-2013, ಸೋಮವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0140.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0140.jpg" alt="`ಔಪನಿಷದ ಪುರುಷ - 43' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ - 26-11-2013, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0141.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0141.jpg" alt="`ವೇದಾಂತರಾಜಹಂಸ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಸುದಿನಂ-27' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು - 7-7-2012, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0142.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0142.jpg" alt="`ಅದ್ವೈತಜ್ಞಾನಸಿಂಧು' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ `ಉಪನಯನಂ-42' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಗೌರವ ಸನ್ಮಾನ, 28-10-2013, ಸೋಮವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0143.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0143.jpg" alt="ಮಹಾಮಹೋಪಾಧ್ಯಾಯ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ ಔಪನಿಷದ ಪುರುಷ - 43 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು, 26-11-2013, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0144.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0144.jpg" alt="`ವೇದಾಂತಪ್ರಭಾಕರ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಉಪನಯನಂ - 42' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತಾಭಿಮಾನಿಗಳು 28-10-2013, ಸೋಮವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0145.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0145.jpg" alt="ವೇದಾಂತಕಾಮಧೇನು' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಉಪದೇಶಸಿಂಚನಂ-26' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು, 16-6-2012, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0146.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0146.jpg" alt="`ವೇದಾಂತವಾರಿಧಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಔಪನಿಷದ ಪುರುಷ - 43' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಜಿಜ್ಞಾಸುಗಳು - 26-11-2013, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0147.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0147.jpg" alt="ವೇದಾಂತಕೇಸರಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಸಂಸ್ಕೃತ ವೈಭವ-44' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು ; 30-12-2013, ಸೋಮವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0149.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0149.jpg" alt="`ತೈತ್ತಿರೀಯದ ತಿರುಳು-45' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗೌರವಪೂರ್ವಕ ಸನ್ಮಾನ, 30-1-2014, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0151.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0151.jpg" alt="30-1-2014, ಗುರುವಾರದಂದು `ವೇದಾಂತಚಕ್ರವರ್ತಿ' ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ತೈತ್ತಿರೀಯದ ತಿರುಳು' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0154.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0154.jpg" alt="`ಅದ್ವೈತವೇದಾಂತಸವ್ಯಸಾಚಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ತೈತ್ತಿರೀಯದ ತಿರುಳು-45' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ. 30-1-2014, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0155.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0155.jpg" alt="`ವೇದಾಂತಪ್ರವಚನಚತುರ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಸಂಸ್ಕೃತ ವೈಭವ -44' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು, 30-12-2013, ಸೋಮವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0157.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0157.jpg" alt="ರಾಮಾಂಜನೇಯ-46' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ `ಉಪನಿಷದ್ ರತ್ನಾಕರ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಪಂತಿಗಳಿಗೆ ಗೌರವ ಸನ್ಮಾನ, 26-2-2014, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0158.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0158.jpg" alt="`ವೇದಾಂತರತ್ನಾಕರ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಸಂಸ್ಕೃತ ವೈಭವ-44' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸಂಸ್ಕೃತಾಭಿಮಾನಿಗಳು, 30-12-2013, ಸೋಮವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0159.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0159.jpg" alt="`ಮುಮುಕ್ಷುಮೋಕ್ಷಧೇನು' ವಿದ್ವಾನ್ ಕೆ. ಜೆ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ರಾಮಾಂಜನೇಯ-46' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು, 26-2-2014, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0161.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0161.jpg" alt="`ಜಿಜ್ಞಾಸು ಕಾಮದೇನು' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಸಂಸ್ಕೃತ ವೈಭವ-44' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀ ಶರ್ಮಾದಂಪತಿಗಳಿಗ ಗೌರವಸನ್ಮಾನ, 30-12-2013" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0162.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0162.jpg" alt="`ವೇದಾಂತ ಪರುಷಮಣಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ರಾಮಾಂಜನೇಯ-46' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತಾಭಿಮಾನಿಗಳು, 26-2-2014, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0163.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0163.jpg" alt="`ವೇದಾಂತಪುರುಷಮಣಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ತತ್ತ್ವಮಸಿ-48' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು, 22-4-2014, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0165.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0165.jpg" alt="`ಉಪನಿಷದ್‍ರತ್ನಾಕರ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾಜಿಯವರ `ಬ್ರಹ್ಮಜ್ಞಾನಫಲಂ'-49 ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ, 16-5-2014, ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0167.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0167.jpg" alt="`ಮುಮುಕ್ಷುಮೋಕ್ಷಧೇನು', `ವೇದಾಂತಚಕ್ರವರ್ತಿ', ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಬ್ರಹ್ಮಜ್ಞಾಲಫಲಂ'-49 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ, 16-5-2014, ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0170.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0170.jpg" alt="`ಜಿಜ್ಞಾಸುಕಾಮಧೇನು' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ತತ್ತ್ವಮಸಿ'-48 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ, 22-4-2014, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0171.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0171.jpg" alt="`ಜಿಜ್ಞಾಸುಕಾಮಧೇನು', `ಮಹಾಮಹೋಪಾಧ್ಯಾಯ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಜ್ಞಾನಸಾಧನಗಳು'-50 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭ, 28-6-2014. ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0173.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0173.jpg" alt="`ವಿದ್ಯಾವಿಧಿನಿಧಿ', `ಮಹಾಮಹೋಪಾಧ್ಯಾಯ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ತತ್ತ್ವಮಸಿ'-48, ಕೃತಿರತ್ನದ ಸಮಾರಂಭದಲ್ಲಿ ಅಭಿಮಾನಿಗಳು, 22-4-2014, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0174.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0174.jpg" alt="`ರಾಷ್ಟ್ರರತ್ನ', `ಮಹಾಮಹೋಪಾಧ್ಯಾಯ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `108 ಅಷ್ಟಕ ಸ್ತೋತ್ರಗಳು'-51 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ, 31-7-2014, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0175.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0175.jpg" alt="`ವೇದಾಂತ ರತ್ನ', `ಮಹಾಮಹೋಪಾಧ್ಯಾಯ' ಡಾ ॥ ಕೆ. ಜೆ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `108 ಅಷ್ಟಕ ಸ್ತೋತ್ರಗಳು'-51 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭ, 31-7-2014" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0176.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0176.jpg" alt="`ಅಧ್ಯಾತ್ಮವಿದ್ಯಾಪ್ರವೀಣ' ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಜ್ಞಾನಸಾಧನಗಳು'-50 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭ, 28-6-2014, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0177.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0177.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `108 ಅಷ್ಟಕ ಸ್ತೋತ್ರಗಳು'-51 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ, 31-7-2014, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0178.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0178.jpg" alt="`ಶಾಂಕರಾದ್ವೈತವೇದಾಂತಾಚಾರ್ಯ' ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಬ್ರಹ್ಮಜ್ಞಾನಫಲಂ'-49 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ, 16-5-2014, ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0179.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0179.jpg" alt="ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಚತುಷ್ಟಯ ಸಂಗ್ರಹ'-52 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು 30-8-2014, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0180.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0180.jpg" alt="ವೇದಾಂತಚಕ್ರವರ್ತಿ, ವೇದಾಂತಪ್ರಭಾಕರ, ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಚತುಷ್ಟಯ ಸಂಗ್ರಹ'-52, ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ - 30-8-2014" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0181.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0181.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಚತುಷ್ಟಯ ಸಂಗ್ರಹ'-52, ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಮತಿ ಕೆ. ಶಾರದಾರಾಜುರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 30-8-14, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0182.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0182.jpg" alt="ಮಹಾಮಹೋಪಾಧ್ಯಾಯ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ಚತುಷ್ಟಯ ಸಂಗ್ರಹ'-52 ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ, 30-8-2014" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0183.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0183.jpg" alt="ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಸಂಗ್ರಾಹಕ ಶೋಕ್ಲಗಳು'-53 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು 27-9-2014, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0184.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0184.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಚತುಷ್ಟಯ ಸಂಗ್ರಹ'-52, ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸುಬ್ರಾಯಶರ್ಮರು ಮಾತನಾಡುತ್ತಿರುವುದು, 30-8-2014, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0185.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0185.jpg" alt="ಭುವಿವೇದಾಂತೃಕಶ್ರೇಷ್ಠರತ್ನ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ಸಂಗ್ರಾಹಕ ಶ್ಲೋಕಗಳು'-53 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ, 27-9-14, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0186.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0186.jpg" alt="ಅದ್ವೈತವೇದಾಂತಸಾರಥಿ, ಜಿಜ್ಞಾಸುಕಾಮಧೇನು ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಸಂಗ್ರಾಹಕ ಶ್ಲೋಕಗಳು'-53 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ, 27-9-2014" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0187.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0187.jpg" alt="`ವೇದಾಂತಚಕ್ರವರ್ತಿ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶ್ರೀಶ್ರೀಗಳ ಸಂಶೋಧನೆ'-54 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು, 19-10-2014, ಭಾನುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0188.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0188.jpg" alt="`ವೇದಾಂತಚಕ್ರವರ್ತಿ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಮಹರ್ಷಿಗಳ ಅಷ್ಟಕ ಸ್ತೋತ್ರಗಳ'-55 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣದ ಶುಭಸಮಾರಂಭದಲ್ಲಿ ಅಧ್ಯಕ್ಷಪೀಠದಿಂದ ಪ್ರೋ ॥ ಡಾ ॥ ಮಲ್ಲೇಪುರಂ ಜಿ. ವೆಂಕಟೇಶರವರು ಮಾತಾಡುತ್ತಿದ್ದಾರೆ. 11-11-14, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0189.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0189.jpg" alt="`ಶಾಸ್ತ್ರನಿಧಿ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶ್ರೀಶ್ರೀಗಳ ಸಂಶೋಧನೆ'-54 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶರ್ಮಾದಂಪತಿಗಳಿಗೆ `ಗೌರವ ಸನ್ಮಾನ'. 19-10-2014, ಭಾನುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0190.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0190.jpg" alt="`ಮುಮುಕ್ಷುಮೋಕ್ಷಧೇನು' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶ್ರೀಶ್ರೀಗಳ ಸಂಶೋಧನೆ'-54 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಜಿಜ್ಞಾಸು ಶ್ರೋತೃಗಳು. 19-10-2014, ಭಾನುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0191.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0191.jpg" alt="`ಜಿಜ್ಞಾಸುಕಾಮಧೇನು' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ಮಹರ್ಷಿಗಳ ಅಷ್ಟಕ ಸ್ತೋತ್ರಗಳು'-55 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು 11-11-2014, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0192.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0192.jpg" alt="`ಶಾಂಕರಾದ್ವೈತವೇದಾಂತಾಚಾರ್ಯ' ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಮಹರ್ಷಿಗಳ ಅಷ್ಟಕ ಸ್ತೋತ್ರಗಳು'-55 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ಆರ್. ಎನ್. ನಾಗರಾಜರವರು ಮಾತಾಡುತ್ತಿದ್ದಾರೆ. 11-11-2014, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0193.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0193.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಮಹರ್ಷಿಗಳ ಅಷ್ಟಕ ಸ್ತೋತ್ರಗಳು'-55 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಶರ್ಮಾದಂಪತಿಗಳಿಗೆ `ಗೌರವ ಸನ್ಮಾನ'. 11-11-14, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0194.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0194.jpg" alt="`ವೇದಾಂತ ಪರುಷಮಣಿ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ಮಹರ್ಷಿಗಳ ಅಷ್ಟಕ ಸ್ತೋತ್ರಗಳು'-55 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಪ್ರವಚನ ಶ್ರೋತೃಗಳು 11-11-14, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0195.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0195.jpg" alt="`ವೇದಾಂತಪುರುಷಮಣಿ' ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶಾಂಕರಮಕರಂದ'-56 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು; 30-12-2014, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0196.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0196.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ನೀತಿಶ್ಲೋಕಗಳು'-57 ಕೃತಿಯನ್ನು ಶ್ರೀ ಕೆ. ಎಸ್. ಎಲ್. ಎನ್. ಸ್ವಾಮಿ, ಶ್ರೀಮತಿ ಬಿ. ವಿ. ರಾಧಾರವರು ಲೋಕಾರ್ಪಣೆ  ಮಾಡುತ್ತಿದ್ದಾರೆ. 20-1-15, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0197.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0197.jpg" alt="`ವೇದಾಂತರತ್ನಾಕರ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ನೀತಿಶ್ಲೋಕಗಳು'-57 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಸನ್ಮಾನ. 20-1-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0198.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0198.jpg" alt="ಮಹಾಮಹೋಪಾಧ್ಯಾಯ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶಾಂಕರಮಕರಂದ'-56 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಭಾಷ್ಯಜಿಜ್ಞಾಸುಗಳು. 30-12-2014, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0199.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0199.jpg" alt="ಮುಮುಕ್ಷುಮೋಕ್ಷಧೇನು' ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ನೀತಿಶ್ಲೋಕಗಳು'-27 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಗಣ್ಯ ಅತಿಥಿಗಳು. 20-1-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0200.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0200.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರು `ಶಾಂಕರಮಕರಂದ'-56 ಗ್ರಂಥ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ವಿಜಯೇಂದ್ರ ಮುನಿಕೋಟಿ (ಜರ್ಮನಿ) ಮಾತಾಡುತ್ತಿದ್ದಾರೆ. 30-12-2014, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0201.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0201.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ನೀತಿಶ್ಲೋಕಗಳು'-57 ಗ್ರಂಥವನ್ನು ಲೋಕಾರ್ಪಣೆಮಾಡಿದ ಬಳಿಕ ಶ್ರೀ ಕೆ. ಎಸ್. ಎಲ್. ಎನ್. ಸ್ವಾಮಿ ರವೀ ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 20-1-15 ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0202.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0202.jpg" alt="ಶಾಸ್ತ್ರನಿಧಿ' ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ನೀತಿಶ್ಲೋಕಗಳು'-57 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತ ಅದ್ಯಾತ್ಮಪ್ರೇಮಿಗಳು. 20-1-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0203.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0203.jpg" alt="`ವೇದಾಂತಸಾರ್ವಭೌಮ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಕೈವಲ್ಯೋಪನಿಷತ್'-58 ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಮುಖ್ಯ ಅತಿಥಿಗಳು; 24-2-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0205.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0205.jpg" alt="`ಶಾಸ್ತ್ರವಿದ್ಯಾನಿಧಿ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ವಿವೇಕರತ್ನ'-59 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ. 17-3-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0206.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0206.jpg" alt="`ಉಪನಿಷದ್ರತ್ನಾಕರ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಕೈವಲ್ಯೋಪನಿಷತ್'-58 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಪ್ರೀತಿಯ ವೇದಾಂತಾಭಿಮಾನಿಗಳು. 24-2-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0207.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0207.jpg" alt="`ವಿವೇಕಭಾಸ್ಕರ' ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ವಿವೇಕರತ್ನ'-59 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಗಣ್ಯ ಅತಿಥಿಗಳು; 17-3-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0208.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0208.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ಕೈವಲ್ಯೋಪನಿಷತ್'-58 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ, 24-2-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0209.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0209.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಕೈವಲ್ಯೋಪನಿಷತ್'-58 ಗ್ರಂಥವನ್ನು ಲೋಕಾರ್ಪಣೆಮಾಡುತ್ತಿರುವ ಶ್ರೀಮತಿ ನಳಿನಿಕುಮಾರ್ ಮತ್ತು ಶ್ರೀ ಬಿ. ಕೆ. ಕುಮಾರ್‍ರವರು ಹಾಗೂ ಡಾ ॥ ವಿ. ರಾಮು ಹಾಗೂ ಶ್ರೀಮತಿ ರುಕ್ಮಿಣಿ ರಾಮು (U.S.A.) ರವರು. 24-2-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0210.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0210.jpg" alt="`ಜಿಜ್ಞಾಸುಕಾಮಧೇನು' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ `ವಿವೇಕರತ್ನ'-59 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ತತ್ತ್ವಜಿಜ್ಞಾಸು ಸಾಧಕರುಗಳು. 17-3-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0211.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0211.jpg" alt="ವೇದಾಂತಚಕ್ರವರ್ತಿ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಗುರುಶಿಷ್ಯ ಸಂಬಂಧ'-60 ಕೃತಿರತ್ನವನ್ನು ಪೂಜ್ಯ ಶ್ರೀಶ್ರೀಸದಾನಂದಗಿರಿ ಸ್ವಾಮೀಜಿಯವರು ಲೋಕಾರ್ಪಣೆ ಮಾಡುತ್ತಿದ್ದಾರೆ; 18-4-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0213.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0213.jpg" alt="`ವೇದಾಂತರತ್ನಾಕರ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಗುರುಶಿಷ್ಯ ಸಂಬಂಧ'-60 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಗಣ್ಯ ಅತಿಥಿಗಳು ; 18-4-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0214.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0214.jpg" alt="`ವೇದಾಂತಪರುಷಮಣಿ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ, `ಗುರುಶಿಷ್ಯ ಸಂಬಂಧ'-60 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಅಭಿಮಾನಿಗಳಿಂದ `ಗೌರವಸನ್ಮಾನ'; 18-4-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0215.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0215.jpg" alt="`ಅದ್ವೈತಸಾರತಿಲಕ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಲಕ್ಷಣ ಶ್ಲೋಕಗಳು'-61 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಗಣ್ಯ ಅತಿಥಿಗಳು ; 12-5-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0216.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0216.jpg" alt="ಅದ್ವೈತವೇದಾಂತಸಾರಥಿ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಗುರುಶಿಷ್ಯಸಂಬಂಧ'-60 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಶಾಂಕರಭಾಷ್ಯ ಪ್ರವಚದ ಶ್ರೋತೃಗಳು ; 18-4-15, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0217.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0217.jpg" alt="`ಉಪನಿಷದ್ರತ್ನಾಕರ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಗೆ `ಲಕ್ಷಣ ಶ್ಲೋಕಗಳು'-61 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ `ಗೌರವಸನ್ಮಾನ'; 12-5-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0218.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0218.jpg" alt="ಜಿಜ್ಞಾಸುಕಾಮಧೇನು' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಲಕ್ಷಣ ಶ್ಲೋಕಗಳು'-61 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತ ಅಭಿಮಾನಿಗಳು; 12-5-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0219.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0219.jpg" alt="ಅಧ್ಯಾತ್ಮವಿದ್ಯಾಪ್ರವೀಣ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮರ ಭಗವಾನ್ ಶ್ರೀರಮಣ ಮಹರ್ಷಗಳ `ಉಪದೇಶಸಾರ'-62" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0220.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0220.jpg" alt="ಭಗವಾನ್ ಶ್ರೀರಮಣ ಮಹರ್ಷಿಗಳ `ಉಪದೇಶಸಾರ'-62 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಲೇಖಕ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಗೆ `ಗೌರವಸನ್ಮಾನ' 23-6-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0221.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0221.jpg" alt="ಭಗವಾನ್ ಶ್ರೀರಮಣ ಮಹರ್ಷಿಗಳ `ಉಪದೇಶಸಾರ'-62 ಕೃತಿರತ್ನದ ಶ್ರೀರಮಣಭಕ್ತ ಶ್ರೀ ಎನ್. ನಂದಕುಮಾರ್‍ರವರು ಲೋಕಾರ್ಪಣೆ ಮಾಡುತ್ತಿದ್ದಾರೆ. 23-6-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0222.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0222.jpg" alt="ಭಗವಾನ್ ಶ್ರೀರಮಣ ಮಹರ್ಷಿಗಳ `ಉಪದೇಶಸಾರ'-62 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಅಧ್ಯಾತ್ಮಜ್ಞಾನಪಿಪಾಸುಗಳಾದ ಶ್ರೀರಮಣಭಕ್ತರುಗಳು; 23-6-2015, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0223.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0223.jpg" alt="`ಮುಮುಕ್ಷುಮೋಕ್ಷಧೇನು' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಅಜ್ಞಾನವಿಮುಕ್ತಿ'-63 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಗಣ್ಯ ಅತಿಥಿಗಳು; 18-7-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0224.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0224.jpg" alt="`ವೇದಾಂತಪರುಷಮಣಿ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಅಜ್ಞಾನವಿಮುಕ್ತಿ'-63 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತಾಸಕ್ತ ಜ್ಞಾನಪಿಪಾಸುಗಳು; 18-7-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0225.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0225.jpg" alt="`ಉಪನಿಷದ್‍ರತ್ನಾಕರ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಅಜ್ಞಾನವಿಮುಕ್ತಿ'-63 ಕೃತಿರತ್ನವನ್ನು ಸನ್ಮಾನ್ಯರಾದ ಕೆ. ಎನ್. ಕೃಷ್ಣಮೂರ್ತಿಗಳು ಲೋಕಾರ್ಪಣೆಮಾಡುತ್ತಿದ್ದಾರೆ; 18-7-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0226.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0226.jpg" alt="`ಅದ್ವೈತವೇದಾಂತಸಾರಥಿ' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಅಜ್ಞಾನವಿಮುಕ್ತಿ'-63 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ಶರ್ಮಾದಂಪತಿಗಳಿಗೆ `ಗೌರವಸನ್ಮಾನ' 18-7-2015" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0227.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0227.jpg" alt="`ಮುಮುಕ್ಷುಮೋಕ್ಷಧೇನು' ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ವಂದೇ ಶಂಕರಸದ್ಗುರುಂ'-64 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಗಣ್ಯರಾದ ಮುಖ್ಯ ಅತಿಥಿಗಳು; 7-9-2015, ಸೋಮವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0228.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0228.jpg" alt="`ಉಪನಿಷದ್ರತ್ನಾಕರ' ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಗೀತಾ ಸಂವತ್ಸರ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣದಲ್ಲಿ ಮಾತನಾಡುತ್ತಿರುವ ಬಿ. ರಾಘವೇಂದ್ರ ಶೆಣೈರವರು - 11-9-2015, ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0229.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0229.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ವಂದೇ ಶಂಕರಸದ್ಗುರುಂ'-64 ಗ್ರಂಥರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡಿ, ಪ. ಪೂ. ಸದಾನಂದಗಿರಿ ಸ್ವಾಮೀಜಿಯವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 7-9-2015, ಸೋಮವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0230.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0230.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ವಂದೇ ಶಂಕರಸದ್ಗುರುಂ'-64ನೇ ಕುಸುಮ ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಶಂಕರರ ಆರಾಧಕರುಗಳು - 7-9-2015, ಸೋಮವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0231.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0231.jpg" alt="ಮಹಾಮಹೋಪಾಧ್ಯಾಯ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಚತುಸ್ಸೂತ್ರೀಭಾಷ್ಯಸಾರ'-65 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಗಣ್ಯ ಅತಿಥಿಗಳು ; 30-9-2015, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0232.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0232.jpg" alt="ಮುಮುಕ್ಷುಮೋಕ್ಷಧೇನು' ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಚತುಸ್ಸೂತ್ರೀಭಾಷ್ಯಸಾರ'-65 ಕೃತಿ ಅರ್ಪಣೆಮಾಡಿ, ಶ್ರೀ ಕೆ. ಎಂ. ಶ್ರೀನಿವಾಸಭಟ್ಟರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ - 30-9-2015, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0233.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0233.jpg" alt="`ಚತುಸ್ಸೂತ್ರೀಭಾಷ್ಯಸಾರ'-65 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಲೇಖಕ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಸದ್ಗುರುಭಕ್ತರಿಂದ ಗೌರವಸನ್ಮಾನ - 30-9-2015, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0234.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0234.jpg" alt="`ವೇದಾಂತಪ್ರಭಾಕರ' ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಚತುಸ್ಸೂತ್ರೀಭಾಷ್ಯಸಾರ'-65 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ತತ್ತ್ವಜಿಜ್ಞಾಸುಗಳು  - 30-9-2015, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0235.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0235.jpg" alt="ಭಗವಾನ್ ಶ್ರೀರಮಣಮಹರ್ಷಿಗಳವರ `ಸದ್ದರ್ಶನಂ'-66 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀರಮಣಮಹರ್ಷಿಗಳ ಭಕ್ತರಾದ ಗಣ್ಯ ಅತಿಥಿಗಳು - 21-10-2015, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0236.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0236.jpg" alt="ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ ಭಗವಾನ್ ಶ್ರೀರಮಣಮಹರ್ಷಿಗಳವರ `ಸದ್ದರ್ಶನಂ'-66 ಕೃತಿ ಅರ್ಪಣೆಮಾಡಿ, ಡಾ ॥ ಶಾರದಾನಟರಾಜನ್ ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ- 21-10-2015, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0237.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0237.jpg" alt="ಭಗವಾನ್ ಶ್ರೀರಮಣಮಹರ್ಷಿಗಳವರ `ಸದ್ದರ್ಶನಂ'-66 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀರಮಣಮಹರ್ಷಿಗಳ ಭಕ್ತರಿಂದ ಲೇಖಕ ಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಗೌರವಸನ್ಮಾನ 21-10-2015, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0238.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0238.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ ಭಗವಾನ್ ಶ್ರೀರಮಣಮಹರ್ಷಿಗಳವರ `ಸದ್ದರ್ಶನಂ'-66 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀರಮಣರ ಭಕ್ತರುಗಳು - 21-10-2015, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0239.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0239.jpg" alt="`ಸುಭಾಷಿತ ಸಂವತ್ಸರ' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ; 28-11-2015, ಶನಿವಾರ ಪ್ರೊ ॥ ರಾಮಚಂದ್ರ ಅತ್ತಿಗನಾಳ್, ಎನ್. ಕಾರ್ತಿಕೆಯನ್, ಡಾ ॥ ಅನಸೂಯಾ ಎಸ್. ರಾಜೀವ್, ಸಿ. ಎ. ಸಂಜೀವಮೂರ್ತಿಗಳು ಇವರೊಂದಿಗೆ ಶರ್ಮಾದಂಪತಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0240.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0240.jpg" alt="`ಗೀತೋಪನಿಷತ್'-68 ಗ್ರಂಥವನ್ನು ಲೋಕಾರ್ಪಣೆಮಾಡಿ, ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು (USA)ರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. ಶ್ರೀಮತಿ ರುಕ್ಮಿಣಿ ರಾಮುರವರು ಪಕ್ಕದಲ್ಲಿದ್ದಾರೆ. 31-12-2015, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0241.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0241.jpg" alt="`ತಸ್ಮೈ ಶ್ರೀಗುರವೇ ನಮಃ'-67 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ; 20-11-2015, ಶುಕ್ರವಾರ ಡಾ ॥ ಎಸ್. ಸಪ್ನಾ, ಎಸ್. ಶ್ರೀಹರಿ, ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿ, ಯು. ಹೆಚ್. ಸುಬ್ರಹ್ಮಣ್ಯಂರವರು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0242.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0242.jpg" alt="`ತಸ್ಮೈ ಶ್ರೀಗುರವೇ ನಮಃ'-67 ಗ್ರಂಥವನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡಿದನಂತರ ಡಾ ॥ ಎಸ್. ಸಪ್ನಾರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ ; 20-11-2015, ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0243.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0243.jpg" alt="`ಗೀತೋಪನಿಷತ್ '-68 ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು (USA), ಡಾ ॥ ಶರ್ಮಾದಂಪತಿಗಳೊಂದಿಗೆ ಶ್ರೀಮತಿ ರುಕ್ಮಿಣಿರಾಮು (USA), ಡಾ ॥ ಡಿ. ಸಿ. ರಾವ್ (USA), ಡಾ ॥ ವಿಜಯೇಂದ್ರ ಮುನಿಕೋಟಿ (ಜರ್ಮನಿ), ಡಾ ॥ ಸುಂದರರಾಮನ್‍ರವರು; 31-12-2015, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0245.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0245.jpg" alt="`ಗೀತೋಪನಿಷತ್'-68 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣೆಯಾದಮೇಲೆ ಡಾ ॥ ಡಿ. ಸಿ. ರಾವ್ (USA)ರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. ಉಳಿದ ಅತಿಥಿಗಳೂ ಇದ್ದಾರೆ. 31-12-2015, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0246.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0246.jpg" alt="`ಪ್ರಸ್ಥಾನತ್ರಯಂ'-69 ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಟಿ. ವಿ. ತಿಮ್ಮರಾಜ ಶ್ರೇಷ್ಠಿ, ಬಿ. ಎನ್. ರಂಗಣ್ಣ, ಸಿ. ಕೆ. ಸುಬ್ಬನರಸಿಂಹ, ವಿ ರಾಜಣ್ಣನವರು. 20-1-2016, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0247.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0247.jpg" alt="ಅಧ್ಯಾತ್ಮವಿದ್ಯಾಪ್ರವೀಣ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಪ್ರಥಮ ಪುಸ್ತಕಂ'-70 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಸಚ್ಚಿದಾನಂದಮೂರ್ತಿ, ಕೆ. ಜಿ. ಲಕ್ಷ್ಮೀನರಸಿಂಹಯ್ಯ, ಶ್ಯಾಮಸುಂದರರಾಜನ್, ಎಂ. ಕೃಷ್ಣಮೂರ್ತಿ, ಬಿ. ಸತ್ಯನಾರಾಯಣ ಇದ್ದಾರೆ. 16-2-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0248.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0248.jpg" alt="ವೇದಾಂತಚಕ್ರವರ್ತಿ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬಾರ್ಯಶರ್ಮಾರವರ `ಪ್ರಥಮ ಪುಸ್ತಕಂ'-70 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ವಿದ್ವಾನ್ ಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಸದ್ಗುರುಭಕ್ತರುಗಳಿಂದ ಭಕ್ತಿಗೌರವಪೂರ್ವಕ ಸನ್ಮಾನ; 16-2-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0249.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0249.jpg" alt="`ಪ್ರಥಮ ಪುಸ್ತಕಂ'-70 ಕೃತಿಯನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡಿದ ನಂತರ ಶ್ರೀ ಸಚ್ಚಿದಾನಂದಮೂರ್ತಿಗಳು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 16-2-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0250.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0250.jpg" alt="ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಪ್ರಥಮ ಪುಸ್ತಕಂ'-70 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತಜ್ಞಾನಪಿಪಾಸುಗಳು. 16-2-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0251.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0251.jpg" alt="ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಶಾಂಕರ ಸಂವತ್ಸರ' ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಶ್ರೀ ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿ, ಸಿ. ಎ. ಸಂಜೀವಮೂರ್ತಿ ಎನ್. ಕಾರ್ತಿಕೇಯನ್, ಪಿ. ಆರ್. ಶಿವಶಂಕರ್‍ರವರು; 26-2-2016, ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0252.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0252.jpg" alt="ಶಾಂಕರ ಸಂವತ್ಸರ' ಕೃತಿರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡಿದ ನಂತರ ಸನ್ಮಾನ್ಯರಾದ ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿಗಳು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 26-2-2016, ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0253.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0253.jpg" alt="`ಶಾಂಕರ ಸಂವತ್ಸರ' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಎನ್. ಕಾರ್ತಿಕೆಯನ್‍ರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 26-1-2016, ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0254.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0254.jpg" alt="ವೇದಾಂತ ಮೇರುಕೃತಿ `ಶಾಂಕರ ಸಂವತ್ಸರ'ದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶಾಂಕರಭಾಷ್ಯಪ್ರವಚನಶ್ರೋತೃಗಳಾದ ತತ್ತ್ವಜಿಜ್ಞಾಸುಗಳು; 26-2-2016, ಶುಕ್ರವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0255.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0255.jpg" alt="`ವೇದಾಂಗಗಳು'-72 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು; ಡಾ ॥ ಪ್ರೊ ॥ ಎ. ರಾಮಚಂದ್ರರಾವ್ (USA), ಪ್ರೊ  ॥ ಎನ್. ನಾಗರತ್ನಾ, ಡಾ ॥ ಡಿ. ಶಾಮಣ್ಣ, ಡಾ ॥ ಮಲ್ಲೇಪುರಂ ಜಿ. ವೆಂಕಟೇಶ ಅವರು; 19-4-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0256.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0256.jpg" alt="ವೇದಾಂಗಗಳು'-72 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಪ್ರೊ  ॥ ಮಲ್ಲೇಪುರಂ ಜಿ. ವೆಂಕಟೇಶ ಅವರು ಅಧ್ಯಕ್ಷಪೀಠದಿಂದ ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 19-4-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0257.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0257.jpg" alt="`ಪ್ರಥಮ ಪುಸ್ತಕಂ'-70 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀ ಸಚ್ಚಿದಾನಂದಮೂರ್ತಿಗಳಿಗೆ ಗೌರವ ಸನ್ಮಾನ. 16-2-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0258.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0258.jpg" alt="`ಪ್ರಥಮ ಪುಸ್ತಕಂ'-70 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ; 16-2-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0259.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0259.jpg" alt="ವೇದಾಂಗಗಳು'-72 ಗ್ರಂಥರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡಿದ ನಂತರ ಪ್ರೊ  ॥ ಎ. ರಾಮಚಂದ್ರರಾವ್ ಅವರು ಸಭೆಯನ್ನು ಉದ್ದೇಶಿಸಿ ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 19-4-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0260.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0260.jpg" alt="ಶ್ರೀ ಟಿ. ಕೆ. ತಿಮ್ಮರಾಜಶ್ರೇಷ್ಠಿಯವರು ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾರವರ `ಪ್ರಸ್ಥಾನತ್ರಯಂ'-69 ನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡುತ್ತಿದ್ದಾರೆ. 20-1-2016, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0261.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0261.jpg" alt="`ವೇದಾಂಗಗಳು'-72 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ; 19-4-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0262.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0262.jpg" alt="`ವೇದಾಂಗಗಳು'-72 ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ; 19-4-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0263.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0263.jpg" alt="`ನನ್ನ ಗುರುಕುಲವಾಸ'-71 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀ ಶ್ರೀ ಸದಾನಂದಗಿರಿ ಸ್ವಾಮಿಜಿ, ಶ್ರೀ ಆರ್. ನಾಗರಾಜ, ಶ್ರೀ ಕೆ. ಎಂ. ಶ್ರೀನಿವಾಸಭಟ್ಟರು, ಶ್ರೀ ಯು. ಹೆಚ್. ಸುಬ್ರಹ್ಮಣ್ಯರವರು 12-3-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0264.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0264.jpg" alt="`ಸುಭಾಷಿತ ಸಂವತ್ಸರ' ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ಅನಸೂಯಾ ಎಸ್. ರಾಜೀವ್ ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 28-11-2015, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0265.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0265.jpg" alt="`ನನ್ನ ಗುರುಕುಲವಾಸ'-71 ಗ್ರಂಥರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣೆಮಾಡಿ ಪೂಜ್ಯ ಸದಾನಂದಗಿರಿ ಸ್ವಾಮಿಜಿ ಅವರು ಅನುಗ್ರಹಭಾಷಣವನ್ನು ಮಾಡುತ್ತಿದ್ದಾರೆ, 12-03-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0266.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0266.jpg" alt="`ಗೀತಾಜಯಂತೀ'-73 ಕೃತಿರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡಿ ಸನ್ಮಾನ್ಯ ಬಿ. ಆರ್. ಚಿದಂಬರ ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 14-05-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0267.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0267.jpg" alt="`ಗೀತಾಜಯಂತೀ'-73 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣೆ; ಶ್ರೀಯುತರಾದ ಬಿ. ಆರ್. ಚಿದಂಬರ, ಜಿ. ಎಸ್. ಟಿ. ಪ್ರಭು, ಆರ್. ಮಂಜುನಾಥ್, ಹೆಚ್. ಆರ್. ದಾಶರಥಿ ದೀಕ್ಷಿತರ್ ; 14-5-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0268.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0268.jpg" alt="`ನನ್ನ ಗುರುಕುಲವಾಸ'-71 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣೆ 12-03-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0269.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0269.jpg" alt="`ಗೀತಾಜಯಂತೀ'-73 ಕೃತಿರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಯುತ ಜಿ. ಎಸ್. ಟಿ. ಪ್ರಭು ರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 14-05-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0270.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0270.jpg" alt="ಶ್ರೀಶರ್ಮರ `ನನ್ನ ಗುರುಕುಲವಾಸ'-71 ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಯುತ ಆರ್. ನಾಗರಾಜ ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 12-03-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0271.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0271.jpg" alt="ಶಂಕರಹೃದಯಂ'-74 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ; 15-6-2016, ಬುಧವಾರ; ಶ್ರೀಯುತರಾದ ಬಿ. ಕೆ. ಕುಮಾರ್, ಎಸ್. ರಾಮಚಂದ್ರ ಅಯ್ಯರ್, ಎಸ್. ವಿ. ತೋಳ್ಪಾಡಿ, ಪ್ರಭಾಕರ ಅವರು ಇದ್ದಾರೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0273.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0273.jpg" alt="`ಮಕ್ಕಳಿಗಾಗಿ ಸ್ತೋತ್ರಗಳು'-75 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ; 16-7-2016, ಶನಿವಾರ; ಸನ್ಮಾನ್ಯರಾದ ಟಿ. ರಾಮಕೃಷ್ಣ, ಟಿ. ಕೆ. ಗೀತಾರಾಣಿ, ಟಿ. ನಾಗರಾಜ್, ಎಸ್. ಶಾರದಾ ಸುಬ್ಬರಾಜು ಇದ್ದಾರೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0274.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0274.jpg" alt="`ಶಂಕರಹೃದಯಂ'-74 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ; 15-6-2016, ಬುಧವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0275.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0275.jpg" alt="`ಗೀತೆಯಲ್ಲಿ ಗುಣವಿಮರ್ಶೆ'-76 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ; 9-8-2016, ಮಂಗಳವಾರ; ಸನ್ಮಾನ್ಯರಾದ ಶ್ರೀ ಸಿ. ಎ. ಸಂಜೀವಮೂರ್ತಿ, ಶ್ರೀ ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತ, ಶ್ರೀ ಬಿ. ಜಿ. ನಾಗರಾಜ್, ಶ್ರೀ ಯು. ಎಚ್. ಸುಬ್ರಹ್ಮಣ್ಯಂ ರವರು ಶ್ರೀಶರ್ಮಾದಂಪತಿಗಳೊಂದಿಗೆ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0276.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0276.jpg" alt="`ಗೀತೆಯಲ್ಲಿ ಗುಣವಿಮರ್ಶೆ'-76; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಯುತ ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿಗಳು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 9-8-2016; ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0277.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0277.jpg" alt="`ಗೀತೆಯಲ್ಲಿ ಗುಣವಿಮರ್ಶೆ'-76; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ 9-8-2016, ಮಂಗಳವಾರದಂದು ಗೀತಾಪ್ರಿಯರಾದ ಪ್ರವಚನ ಶ್ರೋತೃಗಳಾದ ಅಭಿಮಾನಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0278.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0278.jpg" alt="`ಗೀತೆಯಲ್ಲಿ ಗುಣವಿಮರ್ಶೆ'-76; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ 9-8-2016, ಮಂಗಳವಾರದಂದು ಲೇಖಕರಾದ ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಆದರದ ಸನ್ಮಾನ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0279.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0279.jpg" alt="ಸದ್ಗುರುಭಾಸ್ಕರ'-77 ಕೃತಿಯ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ; 29-9-2016, ಗುರುವಾರದಂದು; ಶ್ರೀ ಬಿ. ಎಸ್. ಕೃಷ್ಣಮೂರ್ತಿ, ಶ್ರೀಮತಿ ಡಾ ॥ ಆರ್. ಇಂದ್ರಾಣಿ ನಂದಕುಮಾರ್, ಶ್ರೀ ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿ, ಶ್ರೀಮತಿ ಎಂ. ಎನ್. ಲತಾನಾಗೇಶ್ ಅವರೊಂದಿಗೆ ಶ್ರೀಶರ್ಮಾದಂಪತಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0280.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0280.jpg" alt="`ಸದ್ಗುರುಭಾಸ್ಕರ'-77 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ; 29-9-2016, ಗುರುವಾರದಂದು; ಶ್ರೀಮತಿ ಡಾ ॥ ಆರ್. ಇಂದ್ರಾಣಿ ನಂದಕುಮಾರ್ ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0281.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0281.jpg" alt="`ಸದ್ಗುರುಭಾಸ್ಕರ'-77 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ; 29-9-2016, ಗುರುವಾರ; ಲೇಖಕ ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಪ್ರೀತಿಯ ಸನ್ಮಾನ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0282.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0282.jpg" alt="`ಸದ್ಗುರುಭಾಸ್ಕರ'-77 ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶಾಂಕರಭಾಷ್ಯ ಪ್ರವಚನ ಶ್ರೋತೃಗಳಾದ ವೇದಾಂತ ಚಿಂತಕರಾದ ಅಭಿಮಾನಿಗಳು ; 29-9-2016, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0283.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0283.jpg" alt="`ಶಾಂಕರಭಾಷ್ಯಾಮೃತಂ'-78; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಮುಖ್ಯ ಅತಿಥಿಗಳು; ಪೂಜ್ಯ ಸದಾನಂದಗಿರಿ ಸ್ವಾಮಿಗಳು, ಡಾ ॥ ಡಿ. ಎನ್. ನಾಗೇಶ್ ಬಾಬು, ಶ್ರೀ ಪಿ. ಆರ್. ಶಿವಶಂಕರ್ ಮತ್ತು ಶ್ರೀ ಹೆಚ್. ವೇದಮೂರ್ತಿಗಳೊಂದಿಗೆ ಲೇಖಕ ಶರ್ಮಾದಂಪತಿಗಳು; 25-10-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0284.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0284.jpg" alt="`ಶ್ರೀ ಸುರೇಶ್ವರರ ಸಿಂಹಗರ್ಜನೆ'-79 ; ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ; 29-11-2016 ಮಂಗಳವಾರ; ಶಾಂಕರಭಾಷ್ಯಪ್ರವಚನದ ಶ್ರೋತೃಗಳಾದ ಅಧ್ಯಾತ್ಮಜ್ಞಾನಪಿಪಾಸುಗಳಾದ ಅಭಿಮಾನಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0285.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0285.jpg" alt="`ಶಾಂಕರಭಾಷ್ಯಾಮೃತಂ'-78; ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ; 25-10-2016, ಮಂಗಳವಾರ ಲೇಖಕ ವಿದ್ವಾನ್ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಗೌರವ ಸನ್ಮಾನ ಕಾರ್ಯಕ್ರಮ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0286.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0286.jpg" alt="`ಶ್ರೀ ಸುರೇಶ್ವರರ ಸಿಂಹಗರ್ಜನೆ'-79; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ, ಅಭಿಮಾನಿಗಳಿಂದ ಲೇಖಕ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಗೌರವ ಸನ್ಮಾನ ; 29-11-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0287.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0287.jpg" alt="`ಶ್ರೀ ಸುರೇಶ್ವರ ಸಿಂಹಗರ್ಜನೆ'-79; ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ, ಶ್ರೀಯುತರಾದ ಕೆ. ಎಂ. ಕೃಷ್ಣಮೂರ್ತಿ, ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿ, ಡಾ ॥ ಹೆಚ್. ಎಸ್. ಘಳಿಗಿ, ಕೆ. ಎಸ್. ಅನಂತಸ್ವಾಮಿ ಇವರುಗಳ ಜೊತೆಯಲ್ಲಿ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳು ; 29-11-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0288.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0288.jpg" alt="`ಶಾಂಕರಭಾಷ್ಯಾಮೃತ್ಯಂ'-78; ಕೃತಿರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡಿದ ಅನಂತರ ಪೂಜ್ಯ ಶ್ರೀ ಶ್ರೀ ಸದಾನಂದಗಿರಿ ಸ್ವಾಮಿಗಳು ಆಶೀರ್ವಚನ ನೀಡುತ್ತಿದ್ದಾರೆ; 25-10-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0289.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0289.jpg" alt="`ಶ್ರೀ ಸುರೇಶ್ವರರ ಸಿಂಹಗರ್ಜನೆ'-79; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ಹೆಚ್. ಎಸ್. ಘಳಿಗಿಯವರು ಅಧ್ಯಕ್ಷಪೀಠದಿಂದ ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 29-11-2016, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0290.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0290.jpg" alt="`ಶಾಂಕರಭಾಷ್ಯಾಮೃತಂ'-78; ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ; 25-10-2016, ಮಂಗಳವಾರ ಪ್ರತಿದಿನವೂ ಶಾಂಕರಭಾಷ್ಯ ಪ್ರವಚನದ ಶ್ರೋತೃಗಳಾದ ಶ್ರೀಶಂಕರರ ಭಕ್ತರುಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0291.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0291.jpg" alt="`ಉಪಮಾ ಕಾಳಿದಾಸಸ್ಯ'-80; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ; 31-12-2016, ಶನಿವಾರ; ಗಣ್ಯಅತಿಗಳು: ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು U.S.A., ಡಾ ॥ ಡಿ. ಸಿ.ರಾವ್ U.S.A., ಶ್ರೀ ಎನ್. ಕಾರ್ತಿಕೇಯನ್ ಶ್ರೀ ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿಗಳ ಜೊತೆಯಲ್ಲಿ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0292.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0292.jpg" alt="`ಉಪಮಾ ಕಾಳಿದಾಸಸ್ಯ'-80; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಯುತರಾದ ಎನ್. ಕಾರ್ತಿಕೇಯನ್‍ರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 31-12-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0293.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0293.jpg" alt="`ಉಪಮಾ ಕಾಳಿದಾಸಸ್ಯ'-80; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು U.S.A, ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 31-12-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0294.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0294.jpg" alt="`ಉಪಮಾ ಕಾಳಿದಾಸಸ್ಯ'-80; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಆಸೀನರಾಗಿರುವ ಶಾಂಕರಭಾಷ್ಯಪ್ರಿಯರಾದ ತತ್ತ್ವಜಿಜ್ಞಾಸುಗಳು; 31-12-2016, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0295.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0295.jpg" alt="`ಪ್ರಣವೋಪಾಸನಂ'-81; ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ; 31-1-2017 ಮಂಗಳವಾರದಂದು; ಗಣ್ಯ ಅತಿಥಿಗಳೊಂದಿಗೆ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು; ಡಾ ॥ ಡಿ. ಸಿ. ರಾವ್ U.S.A., ಡಾ ॥ ಆರ್. ಎನ್. ನಾಗರಾಜ್, ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು U.S.A., ಡಾ‍  ॥ ಬಿ. ಎಸ್. ರವಿಶಂಕರ್" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0296.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0296.jpg" alt="`ಪ್ರಣವೋಪಾಸನಂ'-81; ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ಆರ್. ಎನ್. ನಾಗರಾಜ್ ಅವರು ಗ್ರಂಥಪರಿಚಯವನ್ನು ಮಾಡಿಸುತ್ತಿದ್ದಾರೆ. 31-1-2017, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0297.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0297.jpg" alt="`ಪ್ರಣವೋಪಾಸನಂ'-81; ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಪ್ರಣವಪ್ರಿಯರಾದ ಅಧ್ಯಾತ್ಮಜ್ಞಾನಪಿಪಾಸುಗಳು; 31-1-2017, ಮಂಗಳವಾರದಂದು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0298.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0298.jpg" alt="`ಪ್ರಣವೋಪಾಸನಂ'-81; ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಡಾ ॥ ಬಿ. ಎಸ್. ರವಿಶಂಕರ್ ಅವರು ಗ್ರಂಥವನ್ನು ಕುರಿತು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 31-1-2017, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0299.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0299.jpg" alt="`ಬ್ರಾಹ್ಮೀಸ್ಥಿತಿಗೆ 40 ಸೋಪಾನಗಳು'-83; ಗ್ರಂಥರತ್ನದ ಬಿಡುಗಡೆ ಸಮಾರಂಭದಲ್ಲಿ ; 25-3-2017, ಶನಿವಾರ ಪರಮಪೂಜ್ಯ ಶ್ರೀ ಶ್ರೀ ಅದ್ವಯಾನಂದೇಂದ್ರಸರಸ್ವತೀ ಸ್ವಾಮಿಗಳು, ಶ್ರೀ ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿ, ಶ್ರೀ ಸಿ. ಎ. ಸಂಜೀವಮೂರ್ತಿಗಳು ಮತ್ತು ಶ್ರೀ ಶ್ರೀಹರಿಯವರೊಂದಿಗೆ ಶ್ರೀ ಶರ್ಮಾದಂಪತಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0300.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0300.jpg" alt="`ಶಾಂಕರಬೋಧಾಮೃತಂ'-84; ಗ್ರಂಥ ಬಿಡುಗಡೆಮಾಡಿ, ಶ್ರೀಯುತ ಸಚ್ಚಿದಾನಂದಮೂರ್ತಿಗಳು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 27-4-2017, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0301.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0301.jpg" alt="`ಬ್ರಾಹ್ಮೀಸ್ಥಿತಿಗೆ 40 ಸೋಪಾನಗಳು'-83; ಗ್ರಂಥ ಬಿಡುಗಡೆಮಾಡಿ, 25-3-2017, ಶನಿವಾರ; ಪರಮಪೂಜ್ಯ ಶ್ರೀ ಶ್ರೀ ಅದ್ವಯಾನಂದೇಂದ್ರಸರಸ್ವತೀ ಸ್ವಾಮಿಗಳವರು ಆಶೀರ್ವಚನವನ್ನು ನೀಡುತ್ತಿದ್ದಾರೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0302.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0302.jpg" alt="`ಬ್ರಾಹ್ಮೀಸ್ಥಿತಿಗೆ 40 ಸೋಪಾನಗಳು'-83; ಕೃತಿರತ್ನದ ಬಿಡುಗಡೆಯ ಸಂದರ್ಭದಲ್ಲಿ ಶಾಂಕರಭಾಷ್ಯಪ್ರಿಯರಾದ ತತ್ತ್ವಜಿಜ್ಞಾಸುಗಳು; 25-3-2017, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0303.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0303.jpg" alt="`ಶಾಂಕರಬೋಧಾಮೃತಂ'-84; ಕೃತಿಯ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ ಶ್ರೀಯುತ ಸಚ್ಚಿದಾನಂದಮೂರ್ತಿ, ಎಂ. ಎಸ್. ಕೃಷ್ಣಮೂರ್ತಿ, ಬಿ. ಜಿ. ನಾಗರಾಜ, ಕೆ. ವಿನಯ್ ಇವರೊಂದಿಗೆ ಡಾ ॥ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳು; 27-4-2017, ಗುರುವಾರದಂದು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0304.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0304.jpg" alt="`ಬ್ರಾಹ್ಮೀಸ್ಥಿತಿಗೆ 40 ಸೋಪಾನಗಳು'-83; ಕೃತಿಯ ಬಿಡುಗಡೆ ಸಮಾರಂಭದಲ್ಲಿ ಲೇಖಕ ಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಸದ್ಗುರುಗಳಿಂದ ಆಶೀರ್ವಾದ ; 25-3-2017, ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0305.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0305.jpg" alt="`ಶಾಂಕರಬೋಧಾಮೃತಂ'-84; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಂದು ಶ್ರೀ ಬಿ. ಜಿ. ನಾಗರಾಜ್‍ರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 27-4-2017, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0306.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0306.jpg" alt="`ಶಾಂಕರಬೋಧಾಮೃತಂ'-84; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಶಾಂಕರಬೋಧಾಮೃತಪ್ರಿಯರಾದ ಜಿಜ್ಞಾಸುಗಳು; 27-4-2017, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0307.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0307.jpg" alt="`ಕವಿಮುನಿಕಂಡ ಶಿವ'-82; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭ; 26-2-2017, ಭಾನುವಾರ; ಪೂಜ್ಯ ಸದಾನಂದಗಿರಿಸ್ವಾಮೀಜಿ, ಡಾ ॥ ಕೆ. ವಿ ರಾಮು (USA), ಶ್ರೀಮತಿ ರುಕ್ಮಿಣಿ ರಾಮು, ಶ್ರೀ ಸಿ. ಎ. ಸಂಜೀವಮೂರ್ತಿ, ಶ್ರೀ ಪಿ. ಆರ್. ಶಿವಶಂಕರ್‍ರವರೊಂದಿಗೆ ಶ್ರೀ ಶರ್ಮಾದಂಪತಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0308.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0308.jpg" alt="`ಕವಿಮುನಿಕಂಡ ಶಿವ'-82; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ; ಡಾ ॥ ಕೆ. ವಿ. ರಾಮು (USA) ಅವರು ಸಭೆಯನ್ನುದ್ದೇಶಿಸಿ ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0309.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0309.jpg" alt="`ಕವಿಮುನಿಕಂಡ ಶಿವ'-82; ಗ್ರಂಥರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ; ಅಧ್ಯಕ್ಷ ಪೀಠದಿಂದ ಸನ್ಮಾನ್ಯ ಪಿ. ಆರ್. ಶಿವಶಂಕರ್‍ರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0310.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0310.jpg" alt="ಕವಿಮುನಿಕಂಡ ಶಿವ'-82; ಗ್ರಂಥ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ ; ತತ್ತ್ವಜಿಜ್ಞಾಸುಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0311.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0311.jpg" alt="`ಪ್ರಬೋಧ ಶ್ಲೋಕಗಳು'-85; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ 23-5-2017, ಮಂಗಳವಾರ ಶ್ರೀ ಶ್ರೀ ಸ್ವರೂಪಾನಂದೇಂದ್ರಸರಸ್ವತೀ ಸ್ವಾಮಿಗಳು, ಬಿ. ಎಸ್. ಕೃಷ್ಣಮೂರ್ತಿ, ಸದಾನಂದಗಿರಿ ಸ್ವಾಮಿಗಳು, ಬಿ. ಕೆ. ಕುಮಾರ್‍ರವರೊಂದಿಗೆ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0312.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0312.jpg" alt="`ಪ್ರಬೋಧ ಶ್ಲೋಕಗಳು'-85; ಗ್ರಂಥರತ್ನವನ್ನು ಲೋಕಾರ್ಪಣೆ ಮಾಡಿದ ಮೇಲೆ; 23-5-17, ಮಂಗಳವಾರ ಪೂಜ್ಯ ಶ್ರೀಶ್ರೀಸ್ವರೂಪಾನಂದೇಂದ್ರಸರಸ್ವತೀ ಸ್ವಾಮಿಗಳವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0313.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0313.jpg" alt="`ಪ್ರಬೋಧ ಶ್ಲೋಕಗಳು'-85; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭದಲ್ಲಿ 23-5-2017, ಮಂಗಳವಾರ ಶ್ರೀಯುತ ಬಿ. ಕೆ. ಕುಮಾರ್‍ರವರು ಸಬೆಯನ್ನು ಉದ್ದೇಶಿಸಿ ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0314.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0314.jpg" alt="`ಪ್ರಬೋಧ ಶ್ಲೋಕಗಳು'-85; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣಸಮಾರಂಭ ; ತತ್ತ್ವಜಿಜ್ಞಾಸುಗಳು." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0315.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0315.jpg" alt="ವೇದಾಂತಡಿಂಡಿಮಸಾರ'-86; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ; 29-06-2017, ಗುರುವಾರ; ವಿದ್ವಾನ್ ಕೆ. ಪಿ. ರತ್ನಾಕರಭಟ್ಟರು, ಶ್ರೀ ವೈ. ಎಸ್. ಸುಬ್ರಹ್ಮಣ್ಯ, ಶ್ರೀ ಪಿ. ಆರ್. ಶಿವಶಂಕರ್, ಶ್ರೀ ಎಸ್. ಶ್ರೀಹರಿಯವರೊಂದಿಗೆ ಲೇಖಕ ಡಾ ॥ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0316.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0316.jpg" alt="`ವೇದಾಂತಡಿಂಡಿಮಸಾರ'-86; ಕೃತಿಯನ್ನು ಲೋಕಾರ್ಪಣ ಮಾಡಿದ ಅನಂತರ ವಿದ್ವಾನ್ ಕೆ. ಪಿ. ರತ್ನಾಕರಭಟ್ಟರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 29-6-2017, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0317.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0317.jpg" alt="`ವೇದಾಂತಡಿಂಡಿಮಸಾರ'-86; ಕೃತಿಯ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ವೈ. ಎಸ್. ಸುಬ್ರಹ್ಮಣ್ಯರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 29-6-2017, ಗುರುವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0318.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0318.jpg" alt="`ವೇದಾಂತಡಿಂಡಿಮಸಾರ'-86; ಕೃತಿಯ ಲೋಕಾರ್ಪಣ ಕಾರ್ಯಕ್ರಮದಲ್ಲಿ ವೇದಾಂತಾಭಿಮಾನಿಗಳು" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0319.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0319.jpg" alt="`ಶತಕತ್ರಯಸಾರ'-87; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭ; 25-7-2017, ಮಂಗಳವಾರ; ಪ್ರೊ ॥ ಟಿ. ಅಶ್ವತ್ಥನಾರಾಯಣರಾವ್, ಶ್ರೀ ಎಂ. ಎಸ್. ಕೃಷ್ಣಮೂರ್ತಿ, ಶ್ರೀ ವರದರಾಜ, ಬೆಳವಾಡಿ (USA) ಶ್ರೀ ಮತ್ತೂರು ಹರಿನಾರಾಯಣರೊಂದಿಗೆ ಲೇಖಕ ಡಾ ॥ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳು." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0320.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0320.jpg" alt="`ಶತಕತ್ರಯಸಾರ'-87; ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಕಾರ್ಯಕ್ರಮದಲ್ಲಿ ವೇದಾಂತಭಾಷ್ಯಪಾಠದ ಅಭಿಮಾನಿಗಳು; 25-7-2017, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0321.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0321.jpg" alt="`ಶತಕತ್ರಯಸಾರ'-87; ಕೃತಿರತ್ನದ ಬಿಡುಗಡೆ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯ ವರದರಾಜ ಬೆಳವಾಡಿ(USA)ಯವರು ಅಧ್ಯಕ್ಷಪೀಠದಿಂದ ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 25-7-2017, ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0322.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0322.jpg" alt="`ವೇದಾಂತಡಿಂಡಿಮಸಾರ'-86; ಗ್ರಂಥರತ್ನದ ಬಿಡುಗಡೆ ಸಮಾರಂಭದಲ್ಲಿ; 29-06-2017, ಗುರುವಾರ ಲೇಖಕ ಡಾ ॥ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾದಂಪತಿಗಳಿಗೆ ಅಭಿಮಾನಿಗಳಿಂದ ಸನ್ಮಾನ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0323.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0323.jpg" alt="ನೈಷ್ಕರ್ಮ್ಯಸಿದ್ಧಿಸಾರ'-89 ನೇ ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ : 26-9-17 ಮಂಗಳವಾರ; ವಿದ್ವಾನ್ ಕೆ. ಎಸ್. ಕೃಷ್ಣಜೋಯಿಸ್, ಡಾ ॥ ಹೆಚ್. ಎಸ್. ಘಳಿಗೆ, ಕೆ. ಎಸ್. ಮಹೇಶಬಾಬು ಮತ್ತು ಆರ್. ಪ್ರಹ್ಲಾದರಾವ್ ಇವರೊಂದಿಗೆ ಲೇಖಕ ವಿದ್ವಾನ್ ಕೆ. ಜಿ. ಸುಬ್ರಾಯಶರ್ಮಾ ದಂಪತಿಗಳಿದ್ದಾರೆ." /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0324.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0324.jpg" alt="ನೈಷ್ಕರ್ಮ್ಯಸಿದ್ಧಿಸಾರ'-89 ನೇ ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣೆ ಮಾಡಿದ ಅನಂತರ ವಿದ್ವಾನ್ ವೇ  ॥ ಕೆ. ಎಸ್. ಕೃಷ್ಣ ಜೋಯಿಸ್ ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 26-9-2017 ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0325.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0325.jpg" alt="`ನೈಷ್ಕರ್ಮ್ಯಸಿದ್ಧಿಸಾರ'-89 ನೇ ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣೆ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಕೆ. ಎಸ್. ಮಹೇಶಬಾಬುರವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 26-9-2017 ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0326.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0326.jpg" alt="`ನೈಷ್ಕರ್ಮ್ಯಸಿದ್ಧಿಸಾರ'-89 ನೇ ಕೃತಿರತ್ನದ ಲೋಕಾರ್ಪಣೆ ಸಮಾರಂಭದಲ್ಲಿ ವೇದಾಂತಪ್ರವಚನ ಶ್ರೋತೃಗಳಾದ ಸದ್ಗುರುಭಕ್ತರುಗಳು; 26-9-2017 ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0327.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0327.jpg" alt="'ಬ್ರಾಹ್ಮೀಸ್ಥಿತಿಗೆ 40 ಸೋಪಾನಗಳು'- 83 ನೇ ಗ್ರಂಥವನ್ನು ಬಿಡುಗಡೆಮಾಡಿದಮೇಲೆ ಪೂಜ್ಯ ಶ್ರೀ  ಶ್ರೀ ಅದ್ವಯಾನಂದೇಂದ್ರಸರಸ್ವತೀ ಸ್ವಾಮಿಗಳವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 25-03-2017 ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0328.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0328.jpg" alt="'ಪ್ರಬೋಧ ಶ್ಲೋಕಗಳು'- 85 ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ; 23-05-2017 ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0329.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0329.jpg" alt="'ಪ್ರಬೋಧ ಶ್ಲೋಕಗಳು'-85 ಕೃತಿಯ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಪೂಜ್ಯ ಶ್ರೀ  ಶ್ರೀಸದಾನಂದಗಿರಿಸ್ವಾಮಿಗಳವರು ಅನುಗ್ರಹಭಾಷಣವನ್ನು ಮಾಡುತ್ತಿದ್ದಾರೆ; 23-05-2017 ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0330.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0330.jpg" alt="'ಬ್ರಾಹ್ಮೀಸ್ಥಿತಿಗೆ ಸೋಪಾನಗಳು'-83 ನೇ ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಶ್ರೀ ಎಸ್. ಆರ್. ಅನಂತಮೂರ್ತಿಗಳವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ. 25-03-2017 ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0331.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0331.jpg" alt="'ಪ್ರಬೋಧ ಶ್ಲೋಕಗಳು'-85 ಕೃತಿಯನ್ನು ಲೋಕಾರ್ಪಣೆಮಾಡಿದನಂತರ ಪೂಜ್ಯ ಶ್ರೀಶ್ರೀಸ್ವರೂಪಾನಂದೇಂದ್ರಸರಸ್ವತೀ ಸ್ವಾಮಿಗಳವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ; 23-05-2017 ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0332.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0332.jpg" alt="'ಬ್ರಾಹ್ಮೀಸ್ಥಿತಿಗೆ 40 ಸೋಪಾನಗಳು'-83 ಕೃತಿ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ; 25-03-2017 ಶನಿವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0333.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0333.jpg" alt="'ಪ್ರಬೋಧ ಶ್ಲೋಕಗಳು'-85 ಗ್ರಂಥದ ಲೋಕಾರ್ಪಣ  ಸಮಾರಂಭದಲ್ಲಿ ಸನ್ಮಾನ್ಯರಾದ ಶ್ರೀಯುತ ಬಿ. ಕೆ. ಕುಮಾರ್ ಅವರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ;23-05-2017 ಮಂಗಳವಾರ" /></div>
      <div class="col-md-3"><img data-original="<?=PUBLIC_URL?>images/gallery/main/002/0334.jpg" src="<?=PUBLIC_URL?>images/gallery/thumb/002/0334.jpg" alt="'ಬ್ರಾಹ್ಮೀಸ್ಥಿತಿಗೆ 40 ಸೋಪಾನಗಳು'-83 ಕೃತಿಯ ಲೋಕಾರ್ಪಣ ಸಮಾರಂಭದಲ್ಲಿ ಡಾ।। ಶರ್ಮಾ ದಂಪತಿಗಳಿಗೆ ಯತಿಪುಂಗವರಿಂದ ಆಶೀರ್ವಾದ; 25-03-2017 ಶನಿವಾರ" /></div>
    </div>
  </div>

  <!-- Scripts -->
  <script>
  	$(window).on('load', function(){
  // jQuery(window).load(function () {
  	var vieweroptions = {
  // inline: true,
  url: 'data-original',
  ready:  function (e) {
  	console.log(e.type);
  },
  show:  function (e) {
  	console.log(e.type);
  },
  shown:  function (e) {
  	console.log(e.type);
  },
  hide:  function (e) {
  	console.log(e.type);
  },
  hidden:  function (e) {
  	console.log(e.type);
  },
  view:  function (e) {
  	console.log(e.type, e.detail.index);
  },
  viewed:  function (e) {
  	console.log(e.type, e.detail.index);
  // this.viewer.zoomTo(1).rotateTo(180);
}
};

var viewer = new Viewer(document.getElementById('imageview'),vieweroptions);
});
</script>
